"""Identity and session lifecycle: the whole of requirement R1's business logic.

Registration, credential verification, token-pair issuance, refresh rotation with reuse
detection, and revocation on logout. This is the first authentication code this repository has
ever contained - the source branch has no role, no permission, no owner and no principal
anywhere - so every rule below is stated here rather than inherited from somewhere older.

Authority is decided here, on the server
----------------------------------------
Nothing a caller sends decides what they may become. :class:`~app.schemas.auth.RegisterRequest`
has no ``role`` field and forbids unknown keys, so ``{"role": "ADMIN"}`` in a registration body
is a ``422`` rather than a privilege quietly granted; the role a new account receives is chosen
by :meth:`AuthService.register` and by the ``'READER'::user_role`` server default behind it.
``ADMIN`` is reachable only by seeding (``app.db.seed``) or by an existing administrator through
``admin_service`` - never by self-registration, and never by anything in this file.

The client also supplies no identifier and no timestamp. ``id`` comes from PostgreSQL's
``gen_random_uuid()``, the audit instants come from the database clock, and the two ``CITEXT``
UNIQUE indexes on ``users.email`` and ``users.username`` - not the pre-check in
:meth:`AuthService.register` - are what actually make a duplicate account unstorable.

Two failures that must stay indistinguishable
---------------------------------------------
An authentication API leaks its user list through the *difference* between its refusals, so two
pairs of paths are deliberately collapsed here:

* **Login.** An unknown email and a wrong password raise the same class with the same
  :data:`_INVALID_CREDENTIALS` message, and both pay the same argon2 verification cost - the
  unknown-email path verifies against :func:`~app.core.security.dummy_password_hash_async`
  precisely
  so the timing cannot be read as "is this address registered?".
* **Registration.** A taken email and a taken username raise the same
  :class:`~app.core.exceptions.ConflictError` with the same :data:`_IDENTIFIER_TAKEN` message,
  so a caller learns that *something* collided and never *which* - otherwise the registration
  route becomes an oracle for both the address list and the handle list.

Deactivation is the one refusal that is deliberately *not* collapsed into those, because it is a
different question: the credential was genuine. It answers ``403`` with the same message
``get_current_active_user`` uses, so a client sees one consistent story about a suspended
account whether it is signing in or presenting a token it already holds.

Only hashes are persisted, and only once
----------------------------------------
Two secrets pass through this module and neither is stored as given. A password is argon2id
hashed by :func:`~app.core.security.hash_password_async` and the plaintext is dropped when the call
returns. A refresh token is generated by :func:`~app.core.security.generate_refresh_token`,
returned to the caller exactly once inside a :class:`~app.schemas.auth.TokenPair`, and reaches
the database only as the SHA-256 digest from :func:`~app.core.security.hash_refresh_token`. A
database disclosure therefore yields no usable session and no usable password, and neither
value is ever a log field: the only line this module emits carries a user identifier and a
count.

Rotation is one atomic claim, and reuse is a security event
-----------------------------------------------------------
:meth:`AuthService.rotate_refresh_token` spends the presented token through
:meth:`~app.repositories.user_repository.RefreshTokenRepository.claim`, which tests and revokes
the row in a single ``UPDATE ... RETURNING`` under one row lock. That is what makes a refresh
token single-use in the presence of concurrency: reading the row and revoking it afterwards
would let two requests presenting one digest both conclude it was good and both mint a
replacement.

A claim that comes back empty is then *diagnosed* through
:meth:`~app.repositories.user_repository.RefreshTokenRepository.get_by_hash`, which filters
nothing and so can see a row that is already spent. A digest presented twice is the observable
signature of a leaked token, so it is answered by revoking every token the account still holds -
the whole family, not merely the row presented - and by emitting the one log line this module
writes. Everything else about a failed exchange is answered identically, because telling a
caller which check failed is telling an attacker which one to fix.

What this module is, and is not
-------------------------------
* **Business rules only.** No SQL, no statement, no session construction: every query lives in
  ``app.repositories``, reached through the barrel, and this file never imports
  ``app.db.session``.
* **No HTTP concern.** No ``fastapi`` import, no ``HTTPException``, no status-code literal, no
  response envelope. Failures leave as the domain classes in ``app.core.exceptions`` and
  ``app.api.v1.routers.auth`` renders them - the previous service raised
  ``HTTPException(404, "Item not found")`` from inside three separate data-access loops
  (``app.py:L31``, ``L40``, ``L49``) and wrapped results in a ``message``/``data`` envelope
  (``app.py:L18``, ``L39``); neither pattern reappears here.
* **No cryptography.** ``PyJWT`` and ``pwdlib`` are reached only through ``app.core.security``,
  which owns them, so hashing parameters and token claims have exactly one definition site.
* **No configuration reading.** Lifetimes come from ``settings``; there is no environment
  access and no hard-coded secret or duration anywhere below.
* **Schema-shaped results.** Token operations return :class:`~app.schemas.auth.TokenPair` and
  identity operations return the mapped :class:`~app.models.user.User`, which the router
  projects into ``UserPublic`` or ``UserMe``. Never an ad-hoc dictionary.
* **No module-level mutable state.** Only the immutable constants below, and a repository is
  bound to a session per instance rather than shared - the opposite of the ``items = []``
  process-global the previous service used as its entire datastore (``app.py:L6-L7``).

The transaction boundary belongs to this layer
----------------------------------------------
``app.repositories`` flushes and never commits, so each mutating method here commits its own
unit of work and lets every exception propagate: ``get_db`` rolls the session back on the way
out, and the suite's fixture rolls each test back afterwards. Rotation commits **once**, inside
:meth:`AuthService.issue_token_pair`, so the claim that spends the old token and the row that
records its replacement become durable together - a token can never be spent without a
replacement existing.

``session.begin()`` is never called. The session arrives already inside a transaction in both
callers - ``get_db`` in the API tier and the transactional fixture in the suite - and opening a
second one would collide with the outer transaction the suite rolls back.
"""

from __future__ import annotations

import uuid
from typing import Final, NoReturn

from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.exceptions import (
    ConflictError,
    ForbiddenError,
    UnauthorizedError,
    integrity_constraint_name,
)
from app.core.logging import get_logger
from app.core.security import (
    create_access_token,
    dummy_password_hash_async,
    generate_refresh_token,
    hash_password_async,
    hash_refresh_token,
    refresh_token_expires_at,
    verify_password_async,
)
from app.models import User, UserRole
from app.repositories import RefreshTokenRepository, UserRepository
from app.schemas.auth import LoginRequest, RegisterRequest, TokenPair

__all__ = ["AuthService"]


# ---------------------------------------------------------------------------------------
# Refusal messages
#
# Constants rather than inline literals, because the *sameness* of two messages is a security
# property here rather than a matter of tidiness. Two call sites raising "the same" refusal by
# each spelling it out is how the two quietly diverge - a comma added to one of them turns the
# login route back into an account-enumeration oracle, and no test that asserts on either
# message alone would notice. Naming each message once makes the two paths byte-identical by
# construction, which is what `backend/tests/integration/test_auth_api.py` asserts.
#
# Every string below is written to be safe in front of an unauthenticated caller: none names a
# column, an identifier, a configuration value or the existence of any account.
# ---------------------------------------------------------------------------------------

_IDENTIFIER_TAKEN: Final[str] = "That email address or username is already registered."

_REGISTRATION_UNIQUE_CONSTRAINTS: Final[frozenset[str]] = frozenset(
    {"ix_users_email", "ix_users_username"}
)
"""The only two constraints a concurrent registration can legitimately violate.

Both are unique ``citext`` indexes created under these names by revision ``0001``, and both mean
exactly what :data:`_IDENTIFIER_TAKEN` says. Every other constraint on ``users`` describes an
invariant this service is supposed to satisfy on its own - a ``NOT NULL`` column it failed to
populate, a check it failed to respect - so a violation of one is a defect here, not a race, and is
re-raised untouched so it surfaces as a ``500`` with frames.
"""

_REGISTRATION_SQLSTATES: Final[frozenset[str]] = frozenset({"23505"})
"""``unique_violation`` - the only class a concurrent registration can produce.

``23503`` is absent because a new account references nothing. ``23502`` and ``23514`` are absent
because a ``NOT NULL`` or check violation means the row assembled above was wrong.
"""

"""Registration conflict, for a taken email **and** for a taken username alike.

Deliberately ambiguous. Reporting which of the two collided would answer "is this address
registered?" and "is this handle taken?" as separate questions, which together enumerate both
columns; the caller learns only that one of the two identifiers needs changing. Raised from the
pre-check and from the ``CITEXT`` unique violation that backs it, so the two are
indistinguishable from outside as well.
"""

_INVALID_CREDENTIALS: Final[str] = "Incorrect email or password."
"""Login failure, for an unknown email **and** for a wrong password alike.

The wording names both fields on purpose: it is accurate in either case, and it is the sentence
a client can render verbatim. See :meth:`AuthService.authenticate` for the matching guarantee
that the two paths also cost the same.
"""

_ACCOUNT_DEACTIVATED: Final[str] = "This account has been deactivated."
"""A genuine credential belonging to a suspended account.

Character-for-character the message ``app.core.dependencies.get_current_active_user`` raises, so
the same account gets the same explanation whether it is signing in or presenting a token it
already holds. Disclosing this is not enumeration: the caller has already proved they hold the
password for the account, so they learn nothing they did not supply.
"""

_INVALID_REFRESH_TOKEN: Final[str] = "The refresh token is invalid or has expired."
"""Every failed exchange at the refresh route, whatever the cause.

One message for a digest that was never issued, one already spent, one past its expiry and one
whose account has since been removed or deactivated. The causes are distinguished internally -
a spent digest triggers family revocation and the module's one log line - but never in the
response, because naming the failed check tells an attacker which one to fix next.
"""


# ---------------------------------------------------------------------------------------
# Policy constants
# ---------------------------------------------------------------------------------------

_REGISTRATION_ROLE: Final[UserRole] = UserRole.AUTHOR
"""The role every self-registered account receives.

``AUTHOR`` rather than ``READER``, so that an account created through
``POST /api/v1/auth/register`` can immediately exercise the create, edit and publish flow the
validation criteria drive end to end; the alternative would make every one of those checks
depend on an administrative promotion that the product has no self-service path for.

It escalates nothing. ``AUTHOR`` confers authorship of *its own* posts and comments and nothing
further: every mutation is still ownership-scoped in ``post_service`` and ``comment_service``,
and the administrative namespace is gated by ``require_admin`` reading this column on the loaded
row. ``ADMIN`` is unreachable from here - it is granted only by ``app.db.seed`` or by an
existing administrator through ``admin_service`` - and ``app.schemas.auth.RegisterRequest``
carries no ``role`` field, so a caller cannot nominate this value at all.

Assigned explicitly rather than left to the column's ``'READER'::user_role`` server default,
which remains the floor for any insert that omits the column, so that the role a registration
grants is legible in this file instead of implied by a DDL clause in revision ``0001``.
"""

_SECONDS_PER_MINUTE: Final[int] = 60
"""Multiplier converting ``ACCESS_TOKEN_EXPIRE_MINUTES`` into ``TokenPair.expires_in``.

Named because the two units are the interesting part: configuration is expressed in minutes so
an operator reads a plausible number, while the wire field is in seconds because that is what
the OAuth 2.0 token response defines and what a client's timer wants.
"""


class AuthService:
    """Every authentication rule this API enforces, bound to one unit of work.

    Constructed per request by ``app.api.v1.routers.auth`` from the session ``get_db`` yields,
    and directly by the suite from its transactional fixture. One instance therefore covers one
    transaction and holds no state beyond the two repositories it wraps, which is what makes it
    safe under concurrency without a lock: nothing here is shared between requests.

    The six operations and how they compose
    ---------------------------------------
    ==============================  ========================================================
    :meth:`register`                Create an account. Returns the mapped user.
    :meth:`authenticate`            Verify a credential. Returns the mapped user, **no
                                    tokens** - separated so the credential rule can be tested
                                    without minting anything.
    :meth:`issue_token_pair`        Mint and record a pair for a user already established.
    :meth:`login`                   :meth:`authenticate` then :meth:`issue_token_pair`, which
                                    is what the login route calls.
    :meth:`rotate_refresh_token`    Spend a refresh token and mint its replacement.
    :meth:`logout`                  Withdraw the caller's own refresh token, idempotently.
                                    Requires the principal: a token belonging to another
                                    account is inert.
    ==============================  ========================================================

    One lock, one order: every token write serialises on the owning ``users`` row
    -----------------------------------------------------------------------------
    Issuing, rotating, withdrawing and sweeping refresh tokens are four writes to the *same*
    logical thing - the set of credentials one account currently holds - performed by four
    different requests that can arrive at once. Each was individually correct and the set was
    not, because none of them serialised against the others.

    The interleaving that lost a revocation: a rotation spends token ``T1`` and is about to
    insert its successor ``T2``; a concurrent sign-out, reuse sweep or administrative
    deactivation runs ``revoke_all_for_user`` and revokes everything it can *see*, which is
    ``T1`` and not ``T2`` because ``T2`` does not exist yet; then the rotation commits ``T2``.
    Both transactions succeed, and the account is left holding a live credential after a request
    whose whole purpose was to leave it holding none. After an administrative suspension that
    token stays usable, and it is usable again if the account is later reactivated.

    A bulk ``UPDATE`` cannot fix this on its own: it locks the rows that exist when it runs, and
    the row that defeats it is the one inserted afterwards. So every writer here takes an
    exclusive lock on the owning ``users`` row **before** touching any token row, through
    :meth:`_lock_account`. Whichever writer arrives second blocks, and because the session runs at
    ``READ COMMITTED`` it then re-evaluates against the state the first one committed - the sweep
    sees the successor and revokes it, or the rotation finds its token already revoked and refuses.

    **The order is not negotiable: the account row first, always.** ``app.services.admin_service``
    already locks it before its deactivation sweep and before deleting an account, so the two
    services share one protocol rather than two. Reversing the order anywhere - taking a token-row
    lock and then asking for the account - introduces a deadlock cycle against every writer that
    does it the documented way, which is why :meth:`rotate_refresh_token` performs an unlocked read
    purely to discover the owner and locks the account before it claims anything.

    Which errors leave here, and what each means
    --------------------------------------------
    Only the three domain classes below, never a framework exception and never a bare
    ``Exception``. The distinction between the ``401`` and the ``403`` is not cosmetic: a client
    that conflates them will try to refresh a perfectly good token in response to a permissions
    failure and loop.

    * :class:`~app.core.exceptions.ConflictError` - ``409``, a registration whose email or
      username is already in use.
    * :class:`~app.core.exceptions.UnauthorizedError` - ``401``, no usable credential: wrong
      password, unknown email, or a refresh token that cannot be exchanged. Carries
      ``WWW-Authenticate: Bearer``.
    * :class:`~app.core.exceptions.ForbiddenError` - ``403``, a genuine credential for a
      deactivated account.

    A :class:`~sqlalchemy.exc.IntegrityError` is caught where one can legitimately occur - the
    registration race - and translated only when the constraint it names is one of the two unique
    indexes on identity, checked through
    :func:`~app.core.exceptions.integrity_constraint_name`. Nothing else is swallowed: a driver or
    programming error must surface as a ``500`` that gets logged and investigated rather than as a
    plausible-looking domain refusal.
    """

    def __init__(self, session: AsyncSession) -> None:
        """Bind this service to one unit of work.

        Args:
            session: The request-scoped :class:`~sqlalchemy.ext.asyncio.AsyncSession` every
                statement runs through, supplied by ``get_db`` in the API tier or by the
                transactional fixture in the suite. Stored so this layer can own the commit,
                which is the boundary ``app.repositories`` deliberately leaves open - it
                flushes and never commits. It is never constructed here, never closed here and
                never wrapped in a further ``begin()``: the session arrives already inside a
                transaction, and opening a second one would collide with the outer transaction
                the suite rolls back after every test.
        """
        self.session = session

        # Both repositories share the one session, so a registration's INSERT and the token row
        # that follows it are the same unit of work and commit together. Constructed here rather
        # than injected: they are thin, session-bound query holders with no configuration of
        # their own, and a test that wants to observe the rows asserts against the database
        # through its own session instead of substituting these.
        self.users = UserRepository(session)
        self.refresh_tokens = RefreshTokenRepository(session)

    # -----------------------------------------------------------------------------------
    # Registration
    # -----------------------------------------------------------------------------------

    async def register(self, payload: RegisterRequest) -> User:
        """Create an account from a validated registration body.

        Everything a caller may decide has already been decided by
        :class:`~app.schemas.auth.RegisterRequest`: the address is a well-formed email, the
        handle matches the URL-safe pattern, and the password clears the length floor and the
        character-variety rule. What is left here is the part a schema cannot see - whether the
        identifiers are free, what the credential becomes, and what authority the account gets.

        Uniqueness is enforced twice, and only the second time counts
        ------------------------------------------------------------
        The pre-check exists to produce a friendly ``409`` in one round trip. It is **not** the
        guarantee: another transaction can claim the same address between that ``SELECT`` and the
        ``INSERT`` below, and no amount of pre-checking closes that window. The two ``CITEXT``
        UNIQUE indexes are the authority, so the insert is wrapped and the violation they raise is
        translated into the *same* conflict the pre-check reports. That is why registering
        ``a@x.com`` and then ``A@X.com`` is a ``409`` rather than a second account or a ``500``:
        ``CITEXT`` compares case-insensitively, and nothing here lower-cases either side, which
        would only hide the constraint that is doing the work.

        Args:
            payload: The validated registration body. Its ``password`` is the only plaintext this
                method sees; it is passed to
                :func:`~app.core.security.hash_password_async` and dropped when that call
                returns, and it is never persisted, echoed or logged.

        Returns:
            The persisted :class:`~app.models.user.User`, with the database-generated ``id`` and
            audit timestamps populated. The router projects it into ``UserPublic``, which has no
            password field to leak the credential back through.

        Raises:
            ConflictError: The email or the username is already registered, whether the pre-check
                below or one of the two unique indexes caught it. The message does not say which
                identifier collided - see :data:`_IDENTIFIER_TAKEN`. An integrity failure on any
                *other* constraint is deliberately **not** translated: it means this method
                assembled a row it should not have, so it propagates and is answered as a ``500``
                with frames. See :data:`_REGISTRATION_UNIQUE_CONSTRAINTS`.
        """
        # One statement with LIMIT 1 rather than two lookups, and the row is returned whole -
        # but nothing here reads it. Which identifier collided is deliberately not inspected,
        # because the message must not depend on it.
        if await self.users.get_by_email_or_username(payload.email, payload.username) is not None:
            raise ConflictError(_IDENTIFIER_TAKEN)

        # Hashed before the entity is built, and on a worker thread rather than on this one.
        # argon2id is configured to spend tens of milliseconds and 64 MiB per call - that cost is
        # the security property, so it is moved off the event loop instead of reduced. Nothing
        # here awaits a session while the hash runs: the uniqueness pre-check above has already
        # returned, and the insert below has not begun.
        password_hash = await hash_password_async(payload.password)

        user = User(
            # Passed through in the case the caller sent it. `CITEXT` makes the comparison
            # case-insensitive, so normalising here would change what the profile displays
            # without changing what the index enforces.
            email=payload.email,
            username=payload.username,
            # The one moment this process holds the plaintext is the argument to the call
            # above; what reaches the column is the encoded argon2id hash it returned.
            password_hash=password_hash,
            # `users.display_name` is NOT NULL and is rendered unconditionally - the byline on
            # every post, the profile heading, the administrative table - so the account is
            # given a usable name now rather than every view having to substitute one. The
            # username is that fallback, exactly as the field's own API description promises.
            display_name=payload.display_name or payload.username,
            # Neither is collected at registration. Both are nullable and both are set later
            # through PATCH /api/v1/users/me; the profile omits the bio block entirely and the
            # avatar primitive renders the account's initials when there is no URL.
            bio=None,
            avatar_url=None,
            role=_REGISTRATION_ROLE,
            # Registration produces a usable account. Deactivation is an administrative action,
            # so there is no email-confirmation gate to hold the flag closed - the prompt asks
            # for sign-up and log-in, and no verification channel exists in this design.
            is_active=True,
        )

        try:
            # `add` flushes and refreshes, so a unique violation surfaces at this call rather
            # than at the commit below - which is why both are inside the same guard.
            persisted = await self.users.add(user)
            await self.session.commit()
        except IntegrityError as violation:
            # The lost half of the race. A failed flush leaves the session unusable until it is
            # rolled back - every later statement would raise `PendingRollbackError` - so the
            # rollback happens here, before the domain error propagates, rather than being left
            # to `get_db`. The transaction held nothing but this insert, so nothing else is
            # discarded.
            await self.session.rollback()

            # WHICH constraint failed decides whether this is a race or a defect, and the two get
            # opposite answers. This used to report every integrity failure as "that email or
            # username is taken", which meant a `NOT NULL` column this method forgot to populate,
            # or a check constraint it violated, was announced to the caller as somebody else's
            # account - a 409 they would retry forever, with no traceback and no 500 to alert on.
            constraint = integrity_constraint_name(violation, sqlstates=_REGISTRATION_SQLSTATES)
            if constraint not in _REGISTRATION_UNIQUE_CONSTRAINTS:
                # Not a race on identity. Re-raised untouched so it surfaces as a 500 with frames,
                # which is the only answer that gets a defect here looked at.
                raise
            # Chained rather than suppressed with `from None`: the caller sees only the `409`,
            # while a traceback keeps the constraint name, which is what separates a genuine
            # race on `ix_users_email` from one on `ix_users_username`. Attaching it discloses
            # nothing, because the engine is built with `hide_parameters=True` - the bound email,
            # username and password hash are never rendered into the exception SQLAlchemy raises.
            raise ConflictError(_IDENTIFIER_TAKEN) from violation

        return persisted

    # -----------------------------------------------------------------------------------
    # Credential verification
    # -----------------------------------------------------------------------------------

    async def authenticate(self, credentials: LoginRequest) -> User:
        """Verify an email and password, and return the account they belong to.

        Deliberately mints nothing. Splitting the credential rule from
        :meth:`issue_token_pair` means the rule can be exercised without writing a token row,
        and it means :meth:`login` reads as the composition it is; the two are joined only
        there.

        Why an unknown email costs as much as a wrong password
        -----------------------------------------------------
        Both refusals raise the same class with the same :data:`_INVALID_CREDENTIALS` message,
        and that alone is not enough - a caller who cannot read the *message* can still read the
        *clock*. Returning early on an unknown address would answer in microseconds while a
        known one spent the full argon2 work factor, and that difference is measurable over a
        handful of requests: it turns this route into an "is this address registered?" API.

        So the verification always runs. When no account matches, it runs against
        :func:`~app.core.security.dummy_password_hash_async` - a real argon2id hash of a value
        drawn from the CSPRNG, which no submitted password can match - and both paths therefore
        pay the same cost before refusing. The dummy hash is cached *and* computed during startup
        by :func:`~app.core.security.warm_password_hashing`, which is what makes the very FIRST
        unknown-email attempt cost the same as the thousandth: left to be computed lazily, that
        first attempt would have paid a whole argon2 hash on top of its verify, and one request is
        enough to read a difference that large.

        Note the ordering below: ``verify_password_async`` is awaited *before* the branch that
        raises, because a branch that skips the call is the timing oracle this exists to close.
        Both refusal paths reach it through the same bounded offload in
        ``app.core.security``, so moving the argon2 cost off the event loop does not
        reintroduce a difference between them - it makes both of them cheaper for every *other*
        request in flight, and neither of them cheaper than the other.

        One available upgrade is deliberately not taken
        ----------------------------------------------
        :func:`~app.core.security.verify_and_update_password` exists so a hash produced with
        outdated argon2 parameters can be replaced during a login - the only moment the plaintext
        is available to re-hash with. It is not used here, because it would turn credential
        verification into a write: this method would acquire a commit, a rollback path and a
        failure mode that signing in does not otherwise have. Re-costing hashes is a deliberate
        operational change, and it belongs to whatever performs that change rather than to every
        sign-in.

        Args:
            credentials: The validated login body. Its ``password`` is not held to the
                registration policy - a password stored before a rule changed must still be
                usable to sign in with - so it arrives length-bounded and nothing more.

        Returns:
            The matching, active :class:`~app.models.user.User`.

        Raises:
            UnauthorizedError: No account carries that email, or the password does not match.
                One class, one message, one cost, for both.
            ForbiddenError: The credential is correct but the account is deactivated. A ``403``
                and not a ``401``, because the caller *is* authenticated and a client that read
                this as a ``401`` would try to refresh a credential that was never the problem.
        """
        user = await self.users.get_by_email(credentials.email)

        # The hash to verify against: the account's when there is one, and an unmatchable
        # stand-in when there is not. Written as a statement rather than a conditional
        # expression only because the stand-in is awaited; which branch is taken is still
        # invisible to the caller, because both then run the same verification below.
        #
        # The stand-in costs one extra offload on the unknown-account path. That asymmetry is
        # deliberate and it is in the safe direction: an unknown email pays *more* than a known
        # one, never less, so it cannot become the fast answer that reveals an address is
        # unregistered. What remains is one token acquisition - tens of microseconds against
        # argon2's tens of milliseconds - because the argon2 run itself is gone from this path
        # entirely: `app.main.lifespan` calls `warm_password_hashing` before the first request, so
        # this await is a cache read even on the first unknown-email attempt the process serves.
        if user is not None:
            stored_hash = user.password_hash
        else:
            stored_hash = await dummy_password_hash_async()

        # Always evaluated, and its result is bound rather than tested inline, so no
        # short-circuit can skip the argon2 cost on the unknown-account path. The verification
        # runs on a bounded worker thread: the cost that closes the timing oracle is paid off the
        # event loop, so a burst of sign-ins queues for a token instead of stalling every other
        # request this worker is serving.
        password_matched = await verify_password_async(credentials.password, stored_hash)

        if user is None or not password_matched:
            raise UnauthorizedError(_INVALID_CREDENTIALS)

        # Checked after the credential rather than before it, so a caller cannot learn that an
        # address belongs to a suspended account without already holding its password.
        if not user.is_active:
            raise ForbiddenError(_ACCOUNT_DEACTIVATED)

        return user

    async def login(self, credentials: LoginRequest) -> TokenPair:
        """Verify a credential and hand back the pair it earns. The sign-in path.

        A composition and nothing more - :meth:`authenticate` then :meth:`issue_token_pair` -
        which exists so ``POST /api/v1/auth/login`` is one call rather than two lines of policy
        transcribed into a route handler. That route calls **this** method, which is what keeps
        the order of the two steps defined once: a handler composing them itself would be a
        second definition of what signing in consists of, and this one would go unused. It is
        also the shape ``app.core.rate_limit`` documents for that route, whose limiter must see
        every attempt including the ones that fail.

        Nothing is written when the credential is refused: :meth:`authenticate` raises before
        :meth:`issue_token_pair` is reached, so a failed sign-in leaves no token row and no
        committed transaction behind.

        Args:
            credentials: The validated login body.

        Returns:
            A freshly minted :class:`~app.schemas.auth.TokenPair`. Its ``refresh_token`` is
            plaintext for the only time it will ever be readable.

        Raises:
            UnauthorizedError: The email is unknown or the password is wrong.
            ForbiddenError: The account is deactivated.
        """
        user = await self.authenticate(credentials)
        return await self.issue_token_pair(user)

    # -----------------------------------------------------------------------------------
    # Token issuance
    # -----------------------------------------------------------------------------------

    async def _lock_account(self, user_id: uuid.UUID) -> User | None:
        """Take the one per-user lock every token write in this service serialises on.

        ``SELECT ... FOR UPDATE`` on the ``users`` row, held until this transaction commits or
        rolls back. The account record is used as the mutex for its *token set* rather than a
        lock being taken over the token rows themselves, and that is the point: the token set's
        membership is what changes, so no row-level lock over the current members can exclude an
        insert that adds a new one. A single, stable row that every writer must hold can.

        Re-entrant within a transaction, so a caller that already holds it may ask again and pay
        only a round trip - which is why :meth:`issue_token_pair` can take it unconditionally even
        when :meth:`rotate_refresh_token` has already done so. That is deliberate: it means no
        future caller of :meth:`issue_token_pair` can insert a token outside the protocol by
        forgetting to lock first.

        Args:
            user_id: The account whose credentials are about to change.

        Returns:
            The locked :class:`~app.models.user.User`, or ``None`` if no such row exists - which
            under ``FOR UPDATE`` is a stronger statement than an ordinary miss: the account was
            not merely absent from a snapshot, it is absent from the committed state, so an
            administrator's delete has already landed.
        """
        return await self.users.get_by_id(user_id, for_update=True)

    async def issue_token_pair(self, user: User) -> TokenPair:
        """Mint an access token and a refresh token for an account already established.

        Called once by :meth:`login` and once by :meth:`rotate_refresh_token`, so a session
        begins the same way whether it was just signed into or just renewed. It performs no
        authority check of its own and must not be reached without one: the caller has either
        verified a password or spent a valid refresh token.

        The two halves are deliberately unalike
        ---------------------------------------
        The **access token** is a signed JWT carrying the subject and the role. It is not
        recorded anywhere, which is exactly why it is short-lived: nothing can withdraw it
        before it expires. The role travels inside it so a client can shape its own interface
        without a round trip - never as the server's authority check, which re-reads the column
        on the loaded row so that a demotion takes effect on the next request rather than
        whenever the token happens to lapse.

        The **refresh token** is opaque entropy, not a JWT: there is nothing inside it to
        decode. It is recorded as a row precisely so it *can* be withdrawn, and only its
        deterministic SHA-256 digest is stored. The plaintext is returned in the response and
        then unrecoverable - not from the database, not from a log - so a disclosure of the
        ``refresh_tokens`` relation yields no usable session.

        Args:
            user: The account the pair is issued to. Persistent, so ``id`` and ``role`` are the
                database's values rather than anything a caller supplied.

        Returns:
            The :class:`~app.schemas.auth.TokenPair`, with ``expires_in`` describing the access
            token's configured lifetime in seconds so a client can schedule its refresh without
            decoding anything.
        """
        # THE lock, taken before any token row is written - see the protocol on this class. Held
        # unconditionally rather than left to the caller: this is the only method that INSERTS a
        # refresh token, so locking here is what makes "no token is ever issued outside the
        # protocol" true by construction rather than by convention. When rotation is the caller it
        # already holds this lock and the re-acquisition costs one round trip.
        locked = await self._lock_account(user.id)
        if locked is None:
            # The account was deleted, and committed, between the caller establishing it and this
            # lock. Refused with the generic 401 - deliberately not one of this module's specific
            # messages, because both callers reach here for different reasons and neither should
            # describe the other's: a sign-in would be wrong to blame the password, and a rotation
            # would be wrong to blame the token. The insert below would otherwise fail on the
            # foreign key and answer 500 for an ordinary, if rare, sequence of events.
            raise UnauthorizedError

        access_token = create_access_token(subject=user.id, role=user.role)

        # The plaintext exists in this frame and in the response, and nowhere else.
        refresh_token = generate_refresh_token()

        # Only the digest crosses into the data layer. Passing `refresh_token` here would store
        # a value no later lookup could match, and every rotation would then fail to find a row
        # that exists - silently, and identically for every user.
        await self.refresh_tokens.create(
            user_id=user.id,
            token_hash=hash_refresh_token(refresh_token),
            # Computed by `app.core.security` from REFRESH_TOKEN_EXPIRE_DAYS as an aware UTC
            # instant. Derived there rather than here so the lifetime has one definition site,
            # and aware because `expires_at` is `timestamptz` - a naive value would be read
            # against the server's session time zone and shift every session's lifetime.
            expires_at=refresh_token_expires_at(),
        )

        # The single commit for this unit of work. When rotation is the caller, the claim that
        # spent the presented token is still uncommitted in this same transaction, so this one
        # statement makes the revocation and its replacement durable together: a token cannot
        # end up spent with no replacement, and a replacement cannot exist while the token it
        # replaced is still exchangeable.
        await self.session.commit()

        return TokenPair(
            access_token=access_token,
            refresh_token=refresh_token,
            # `token_type` is deliberately not passed. It is declared `Literal["bearer"]` with
            # that default on the schema, so the value is already fixed by the contract and can
            # only ever be `"bearer"` - restating it here would put the wire constant in two
            # places, and it would trip the S106 check that the lint configuration keeps
            # ACTIVE precisely so a credential-shaped literal cannot be passed as an argument
            # unnoticed. The response is byte-identical either way.
            expires_in=settings.ACCESS_TOKEN_EXPIRE_MINUTES * _SECONDS_PER_MINUTE,
        )

    # -----------------------------------------------------------------------------------
    # Rotation
    # -----------------------------------------------------------------------------------

    async def rotate_refresh_token(self, raw_token: str) -> TokenPair:
        """Exchange a refresh token for a new pair, spending the presented one.

        The method that makes a refresh token single-use, and the reason this service is more
        than a lookup. Three properties hold together:

        **The exchange is atomic.** The presented digest is spent through
        :meth:`~app.repositories.user_repository.RefreshTokenRepository.claim`, one
        ``UPDATE ... WHERE token_hash = :h AND revoked_at IS NULL AND expires_at > now
        RETURNING ...``, so PostgreSQL evaluates liveness under the same row lock it takes to
        write. Two requests presenting one digest cannot both succeed: the second blocks, re-reads
        the committed ``revoked_at``, matches nothing and comes back empty. Reading the row and
        revoking it afterwards would let both conclude the token was good and both mint a
        replacement, which is single-use in name only.

        **A failed claim is then diagnosed, not guessed.** ``claim`` collapses "never issued",
        "already spent" and "expired" into one empty result, so the *unfiltered*
        :meth:`~app.repositories.user_repository.RefreshTokenRepository.get_by_hash` is asked
        afterwards - it is the only read that can see a row which is already revoked, and seeing
        one is what makes reuse detectable at all.

        **Reuse is treated as a compromise, not a mistake.** A digest that was already exchanged
        being presented again is the observable signature of a leaked token: either the holder
        replayed it, or someone else did. Since it is impossible to tell which party is the
        legitimate one, the whole outstanding family is revoked, forcing a fresh sign-in that only
        the password holder can complete. That is the one event this module logs, because it is a
        genuine security signal rather than routine traffic.

        A token withdrawn by :meth:`logout` and then presented here lands on that same branch, and
        that is intended rather than incidental. A credential the account has already retired is
        being offered in exchange for a new one, and nothing distinguishes a stale client from an
        attacker replaying what they picked up; the conservative reading is the safe one. The
        consequence is real - the account's other sessions end too, and every device signs in
        again - and it is the correct price, because the alternative is to let a withdrawn
        credential be replayed as long as it has not expired.

        Args:
            raw_token: The plaintext refresh token exactly as the client received it. Hashed here
                and never stored, never logged and never compared as text. Not decoded either -
                it is opaque entropy, so there is nothing inside it to read.

        Returns:
            A new :class:`~app.schemas.auth.TokenPair`. The presented token is revoked by the time
            it is returned, and both values must replace the client's previous pair together.

        Raises:
            UnauthorizedError: The token cannot be exchanged - never issued, already spent,
                expired, or belonging to an account that has since been removed or deactivated.
                One message for all five, because naming the failed check tells an attacker which
                one to fix.
        """
        token_hash = hash_refresh_token(raw_token)

        # An UNLOCKED read, for one purpose: to learn which account to lock. It takes no lock, so
        # it cannot participate in a deadlock cycle, and it needs no accuracy beyond the owner -
        # `user_id` never changes on a token row, and every decision below is re-made under the
        # lock. A digest that matches nothing leaves nothing to lock, and `claim` will refuse it
        # on its own terms.
        presented = await self.refresh_tokens.get_by_hash(token_hash)
        if presented is not None:
            # The account row first, BEFORE the claim - see the protocol on this class. Claiming
            # first and locking afterwards would take a token-row lock and then ask for the
            # account, which is the reverse of the order every sweep uses and would deadlock
            # against them. The return value is deliberately unused: whether the account exists and
            # is active is decided below, from the row `claim` hands back, so that a token whose
            # owner vanished is refused by one path rather than two.
            await self._lock_account(presented.user_id)

        # The decision, in one statement, and now made while the account is locked: a sweep that
        # committed while this transaction waited is visible to it, so a token that sweep revoked
        # cannot be claimed here. A row comes back only to the transaction that spent it.
        claimed = await self.refresh_tokens.claim(token_hash)
        if claimed is None:
            # Nothing has been written yet - `claim` matched no row - so there is no write to
            # undo here. Whether the diagnosis performs one is its own decision. It never
            # returns, which is what narrows `claimed` to a row below.
            await self._reject_unclaimable_token(token_hash)

        # The owning account, fetched by its key rather than through `claimed.user`. The
        # relationship keeps SQLAlchemy's default lazy strategy on purpose, so touching it from
        # async context raises `MissingGreenlet` instead of hiding a round trip - and neither
        # `claim` nor `get_by_hash` eager-loads it.
        user = await self.users.get_by_id(claimed.user_id)

        # A cascade removes an account's tokens with it, so a live row whose user is gone means
        # the row was read across that deletion. Reported as the same `401`: a token whose
        # principal does not exist cannot be exchanged, and whether the account was deleted or
        # suspended is not the caller's business.
        if user is None or not user.is_active:
            raise UnauthorizedError(_INVALID_REFRESH_TOKEN)

        # Issues the replacement and commits once, which is what makes the claim above durable.
        # Until this returns, the revocation and the new row are both pending in the same
        # transaction, so any failure between here and the commit leaves the presented token
        # exchangeable rather than destroying a live session.
        return await self.issue_token_pair(user)

    async def _reject_unclaimable_token(self, token_hash: str) -> NoReturn:
        """Explain a failed claim, act on it if it was reuse, and refuse the exchange.

        Split out because the branch does two unrelated things - it decides a security question
        and it always refuses - and because the refusal is uniform while the action is not.
        Called only after :meth:`~app.repositories.user_repository.RefreshTokenRepository.claim`
        has already come back empty, which is what makes the row's state settled: whatever
        transaction was competing for it has committed or rolled back by then.

        Args:
            token_hash: The digest of the presented token, already computed by the caller.

        Raises:
            UnauthorizedError: Always. The cause is resolved here for the sake of the audit trail
                and the family revocation, never for the response.
        """
        # Unfiltered on purpose: a revoked row must be *visible* as revoked, or reuse is
        # indistinguishable from a token that never existed.
        existing = await self.refresh_tokens.get_by_hash(token_hash)

        if existing is not None and existing.revoked_at is not None:
            # Reuse. The digest was exchanged or withdrawn once already, so either it leaked or a
            # client replayed it; there is no way to tell those apart from here, and the safe
            # reading is the hostile one. Revoking the family ends every session the account has
            # open, so an attacker holding a stolen token loses it and the legitimate holder
            # simply signs in again.
            #
            # Locked first, and this sweep is the reason the protocol exists. Without the lock a
            # rotation running beside it inserts a successor the bulk UPDATE cannot see - it locks
            # the rows that exist, and the row that defeats it is the one added afterwards - so the
            # sweep would report success while leaving the compromised family holding a live
            # credential. `rotate_refresh_token` may already hold this lock when it calls here;
            # re-acquiring is a round trip and keeps this method correct when called on its own.
            await self._lock_account(existing.user_id)
            revoked_count = await self.refresh_tokens.revoke_all_for_user(existing.user_id)

            # Committed before raising, so the revocation survives. `get_db` rolls back on an
            # exception, and without this commit the protective sweep would be rolled back with
            # the request that triggered it - leaving the stolen token family live.
            await self.session.commit()

            # Obtained here rather than at module scope, matching `app.core.exceptions` and
            # `app.middleware.request_context`: a logger bound during import memoises
            # structlog's unconfigured defaults, because `configure_logging` runs in
            # `app.main`'s lifespan after every import has completed.
            get_logger(__name__).warning(
                "refresh_token_reuse_detected",
                # The account's server-generated identifier, which is what an operator needs to
                # correlate the event. Never the presented token and never its digest: the token
                # is a live credential, and the digest is the value the UNIQUE index is keyed on,
                # so either in a log is a credential in a log.
                user_id=str(existing.user_id),
                revoked_token_count=revoked_count,
            )
            raise UnauthorizedError(_INVALID_REFRESH_TOKEN)

        # Everything else. Either no token was ever issued with this digest, or the row exists,
        # has never been revoked, and the claim still refused it - which leaves exactly one
        # explanation, that it is past its `expires_at`. Neither is evidence of a leak, so
        # neither triggers the sweep above, and both answer identically.
        raise UnauthorizedError(_INVALID_REFRESH_TOKEN)

    # -----------------------------------------------------------------------------------
    # Revocation
    # -----------------------------------------------------------------------------------

    async def logout(self, raw_token: str, *, actor: User) -> None:
        """End a session by withdrawing the refresh token it was carried by.

        Idempotent, and that is a security decision rather than a convenience. An unknown or
        already-revoked token is accepted silently: raising would make this route answer "does
        this token exist?" and "has it been used?", which is a validity oracle a caller can probe
        without holding any credential at all. It would also fail the honest cases - a retried
        request, a second browser tab, a client signing out twice - for no benefit, since the
        outcome the caller asked for already holds.

        Only the refresh token is withdrawn. The access token is a signed assertion with no
        server-side record, so nothing can retract it before it expires; that is precisely why
        its lifetime is short, and why a client discards it locally on sign-out.

        **A token that is already revoked ends the whole family.** Presenting a withdrawn refresh
        token is the same evidence here as it is at :meth:`rotate_refresh_token`, and it gets the
        same reading: either the token leaked, or a client replayed one it had already spent. The
        second case is not hypothetical - a client that rotates mid-sign-out and then replays its
        original body presents exactly this - and treating it as benign leaves the *successor*
        token live, so the session the caller asked to end is still usable by whatever holds it.
        The response is identical either way, so no oracle is created; only the effect differs.

        The ordinary sign-out is untouched by that rule, because its token has not been revoked
        yet: one live token in, one token out, other sessions on other devices left alone. The
        family sweep is reached only by a token that was already withdrawn, and in that state the
        caller has in any case asked for the session to end.

        **The effect is bound to the presenting principal, and that is what makes the family
        sweep safe to have.** *actor* is required, and a token belonging to any other account is
        treated as if it did not exist: nothing is revoked and nothing is committed. Without that
        check the sweep above was a weapon rather than a protection - anyone with an account of
        their own could present a *stale, already-revoked* token belonging to someone else and end
        every session that victim had open, repeatedly, without ever holding a live credential of
        theirs. The row was located by digest alone, so the account the digest belonged to was in
        effect a caller-supplied parameter naming whose sessions to destroy.

        The refusal is silent, which is the same reasoning as for an unknown token: answering
        differently would turn this route into "does this digest exist, and whose is it?". So a
        foreign token and an unknown token are indistinguishable to the caller - ``204`` either
        way, nothing revoked either way - and only the log records that the two are different
        events.

        Args:
            raw_token: The plaintext refresh token to withdraw. Hashed to locate the row, and
                neither stored nor logged.
            actor: The authenticated account presenting the token, resolved by the route from the
                access token. Keyword-only so a call site cannot pass it positionally where
                *raw_token* belongs, and required so that adding a new caller cannot silently
                reintroduce an unbound revocation.

        Returns:
            ``None``. There is nothing meaningful to report: success, "already ended" and "that
            token is not yours" are one answer, and distinguishing them is the oracle this
            deliberately does not build.
        """
        existing = await self.refresh_tokens.get_by_hash(hash_refresh_token(raw_token))
        if existing is None:
            # Nothing to withdraw and nothing to commit - the session holds no writes, so
            # returning here leaves the transaction exactly as it was found.
            return

        if existing.user_id != actor.id:
            # Someone else's token. Checked BEFORE the replay branch below, and the order is the
            # whole fix: reaching that branch with a foreign token is what let a caller revoke a
            # stranger's entire token family. Nothing is revoked and nothing is committed, so the
            # transaction is left exactly as it was found.
            get_logger(__name__).warning(
                "foreign_refresh_token_presented_at_logout",
                # Both identifiers, because an operator investigating this needs to know who
                # presented the token as well as whose it was - a caller holding a token that is
                # not theirs means it leaked or was captured. Never the token and never its
                # digest: one is a credential and the other is the value the UNIQUE index is
                # keyed on.
                actor_id=str(actor.id),
                token_user_id=str(existing.user_id),
            )
            return

        # THE lock, before either revocation below - see the protocol on this class. A sign-out
        # that did not hold it could run its UPDATE beside a rotation and miss the successor the
        # rotation was about to insert, so the session the caller asked to end would still be
        # alive when the request returned 204. Taken after the ownership check above, because a
        # foreign token must not even cause a lock to be taken on a stranger's account.
        await self._lock_account(actor.id)

        # Re-read under the lock. The state this branch turns on - whether the token is already
        # revoked - was read before the lock was held, and a sweep or a rotation committing in
        # between is exactly what this protocol exists to order. Deciding on the pre-lock snapshot
        # would mean choosing between "revoke this row" and "sweep the family" from a state that
        # is no longer true.
        await self.session.refresh(existing)

        if existing.revoked_at is not None:
            # Already withdrawn, so this is a replay - see the docstring. Ending the family is what
            # makes the request mean what it says: whatever token succeeded this one is what is
            # keeping the session alive, and revoking only this row again would leave it there.
            revoked_count = await self.refresh_tokens.revoke_all_for_user(existing.user_id)
            await self.session.commit()

            # Logged as a warning at the same level as reuse at rotation, because it is the same
            # evidence. Never the presented token and never its digest: one is a live credential
            # and the other is the value the UNIQUE index is keyed on.
            get_logger(__name__).warning(
                "revoked_refresh_token_presented_at_logout",
                user_id=str(existing.user_id),
                revoked_token_count=revoked_count,
            )
            return

        # `revoke` stamps `revoked_at` through `coalesce`, so a repeat preserves the instant the
        # session actually ended rather than overwriting it with the instant of the retry. That
        # first instant is the evidence reuse detection reads, which is why this path must not
        # rewrite it.
        await self.refresh_tokens.revoke(existing)
        await self.session.commit()
