// Client-side validation for the category taxonomy's two request bodies.
//
// This is the single client-side definition site for what an administrator submits when creating
// and when renaming a category — `POST /api/v1/admin/categories` and
// `PATCH /api/v1/admin/categories/{id}`. Both schemas are consumed by
// `@/components/admin/category-form` through `zodResolver`, which that component imports from
// `@hookform/resolvers`; this module imports neither the resolver nor the form library, because a
// schema has no reason to know what renders it.
//
// ONE PAIR OF SCHEMAS, NOT TWO
//
// `app.schemas.admin` on the service side imports `CategoryCreate` and `CategoryUpdate` from
// `app.schemas.category` rather than declaring administrative variants of its own. This module
// mirrors that decision exactly: there is one category-creation contract in this product and one
// category-update contract, so there is no `admin-category.ts` and no administrative variant
// below. A second pair would differ by a bound eventually, and nothing would keep them in step.
//
// The taxonomy's other administrative mutations — a user's role or active flag, a post's
// status, a comment's moderation state — are row-action dropdowns rather than validated forms,
// so they have no schema here or anywhere.
//
// THE CONTRACT THIS MIRRORS, AND WHY THAT MATTERS MORE THAN IT LOOKS
//
// `backend/app/schemas/category.py` is authoritative for every bound and every optionality
// below, and it is the reconciliation point named again at each constraint. The reason for that
// insistence is that drift here fails in a way neither `tsc --noEmit` nor `eslint` can see:
//
//   - a LOOSER client schema lets the form submit a body the API answers with a 422 that names a
//     field the reader was never shown a message for; and
//   - a STRICTER one blocks input the API would have accepted, which reads as a broken form.
//
// Both surface only at runtime, so each constraint below was reconciled against the Pydantic
// model by execution rather than by reading, and the whitespace and blank-folding behaviour in
// particular was compared case by case.
//
// WHAT THESE SCHEMAS DELIBERATELY DO NOT ACCEPT
//
// Neither schema declares `id`, `slug`, `post_count`, `created_at` or `updated_at`, and the
// omissions are the point rather than an oversight:
//
//   - `id` is a UUID generated by PostgreSQL, so a client has nothing to supply.
//   - `slug` is derived from the name by `app.core.slug` once, at creation, and never again. It is
//     the canonical URL: `GET /api/v1/categories/{slug}` resolves against it, the sitemap
//     enumerates it and every canonical link tag is built from it. A form control offering to set
//     or change it would let an administrator invalidate published links, so renaming a category
//     changes the label a reader sees while the address they bookmarked keeps resolving.
//   - `post_count` is a COUNT the API computes to render the home feed's filter chips. It is
//     derived from data, so it can never be submitted.
//   - `created_at` and `updated_at` come from the database clock.
//
// A Zod object strips unknown keys by default, so a form that carries any of them in its state
// still posts a body containing only `name` and `description`. That matters because both service
// models set `extra="forbid"`: an unrecognised member is answered with a 422 rather than ignored,
// and stripping here is what guarantees one is never sent.
//
// Uniqueness is NOT checked here. `categories.name` is UNIQUE and `categories.slug` is a unique
// CITEXT index, so a duplicate is detected where the constraint lives and surfaces as a 409 that
// the form renders as a server error. A client-side check could only ask a stale question, and
// answering it would need an HTTP call this module must not make.
//
// FIELD NAMES ARE snake_case, ON PURPOSE
//
// `name` and `description` are the wire's own names, matching `@/lib/types`. Nothing in this tier
// transforms between casing conventions, so a camelCase field would post a member the API ignores
// while the one it wanted stayed absent. Only the exported identifiers follow JavaScript
// convention: camelCase for the schema constants, PascalCase for the inferred types.
//
// This module carries no `'use client'` directive, so a Server Component and a Client Component
// can both import it. It performs no I/O, reads no environment variable and logs nothing;
// importing it evaluates two schema definitions and nothing else.

import { z } from 'zod';

import { codePointLength } from '@/lib/text';

import type { CategoryCreate, CategoryUpdate } from '@/lib/types';

/**
 * Upper bound on a category name, in characters, measured after surrounding whitespace is removed.
 *
 * Mirrors `NAME_MAX_LENGTH` in `backend/app/schemas/category.py`, which is the reconciliation point
 * if either ever moves. The service sets it equal to its slug bound by intent, so a name accepted
 * at this length yields a slug that fits without being truncated mid-title.
 *
 * Not exported: this module's public surface is the two schemas and their two inferred types, and
 * nothing else. The bound reaches the reader through the message below, which interpolates it, so
 * the number a form reports and the number it enforces cannot disagree.
 */
const NAME_MAX_LENGTH = 80;

/**
 * Upper bound on a category description, in characters, measured after trimming.
 *
 * Mirrors `DESCRIPTION_MAX_LENGTH` in `backend/app/schemas/category.py`. A description is a short
 * paragraph of orientation prose shown on a category listing and in this form — articles are
 * posts — and the category list is fetched on every home-feed render, so each row is paid for
 * repeatedly.
 */
const DESCRIPTION_MAX_LENGTH = 500;

/**
 * Compile-time assertion that `TActual` is assignable to `TContract`, resolving to `TActual`.
 *
 * Applied to each inferred type below, this pins the schemas to the request interfaces in
 * `@/lib/types` — themselves a field-for-field mirror of the Pydantic models — so that widening
 * a field, dropping one, or changing its nullability stops the build with a `TS2344` naming the
 * offending member instead of shipping a form that posts a body the API rejects.
 *
 * Two details of the shape are deliberate. It resolves to `TActual` rather than to `true` or
 * `never`, so wrapping an inferred type in it changes nothing about that type and the exported
 * types stay exactly what `z.infer` produced. And it is applied *inside* the exported type aliases
 * rather than left as standalone assertion aliases, because a standalone one would be unused:
 * `@typescript-eslint/no-unused-vars` warns on an unused type alias even with a leading
 * underscore, and the lint gate runs with `--max-warnings=0`.
 *
 * Being a type alias, it emits no runtime code.
 *
 * Note what it does not do: TypeScript applies excess-property checks to fresh object literals,
 * not to this kind of assignability, so an *extra* member would satisfy the constraint. Keeping
 * server-owned fields out is therefore enforced by not declaring them and by Zod stripping
 * unknown keys, not by this guard.
 */
type AssertAssignableTo<TActual extends TContract, TContract> = TActual;

/**
 * Why every bound in this file is applied through a refinement rather than through zod's `.max()`.
 *
 * `.min()`/`.max()` on a string read `String.prototype.length`, which counts UTF-16 **code units**.
 * The service's constraints are Python `len()`, which counts **code points**. The two agree for ASCII
 * and disagree for every character above `U+FFFF` - an emoji, a historic script, a rare ideograph -
 * which each count as two units and one code point.
 *
 * That divergence breaks the mirror in the direction that matters most here: a ceiling written in code
 * units rejects text the service would have accepted, at exactly half the length for astral text. A
 * reader who writes in one of those scripts is told their perfectly valid comment, title or category
 * name is too long, by a check whose only job was to save them a round trip. `@/lib/validation/auth`
 * already measured this way for its own bounds and recorded two observed cases against the running
 * service; `@/lib/text#codePointLength` is now that measurement, shared by all four validators and by
 * `@/lib/seo`'s truncation, so one notion of length governs the tier.
 *
 * `abort: true` matches the convention in this tier: once a length has failed, later checks on the
 * same field are not run, so one mistake produces one sentence.
 */

/**
 * A category's display label, validated as both request bodies accept it.
 *
 * Declared once and shared, so the create and update schemas cannot drift — the same reason
 * `backend/app/schemas/category.py` declares its `CategoryName` alias once and references it from
 * both models. Mirrors that alias exactly:
 * `StringConstraints(strip_whitespace=True, min_length=1, max_length=80)`.
 *
 * The order of the chain is load-bearing and was verified against the installed Zod: `.trim()`
 * runs before the length checks, so `'  Python  '` is accepted and yields `'Python'`, a padded
 * over-length name is measured after trimming, and `'   '` reaches `.min(1)` as `''` and is
 * rejected rather than being stored as a name that renders as a blank filter chip.
 *
 * The ceiling is measured with `codePointLength` from `@/lib/text` inside a `.refine()` rather than
 * with zod's `.max()`, because `.max()` reads `String.prototype.length` - UTF-16 code units - while
 * the service's `max_length=80` counts Python code points. Without it an eighty-character name
 * written in emoji or an astral script measures 160 here and is refused locally at half the bound
 * the API would have accepted. The floor stays `.min(1)`: for a bound of one the two units cannot
 * disagree, since a string has a code point exactly when it has a code unit.
 *
 * The single message on `z.string()` covers three failures that are one mistake to a reader — the
 * field is missing, is explicitly `null`, or is not a string — which is what makes it correct for
 * both schemas: on a create the field is required, and on an update an explicit `null` is refused
 * because `categories.name` is NOT NULL, matching the service's own `_reject_null_name` validator.
 */
const categoryNameField = z
  .string({ error: 'Enter a category name.' })
  .trim()
  // `.min(1)` stays a length check because "empty" is the same value in either unit; only the ceiling
  // has to be measured the way the service measures it. See the note above.
  .min(1, { error: 'Enter a category name. A name of only spaces is not accepted.' })
  .refine((value) => codePointLength(value) <= NAME_MAX_LENGTH, {
    error: `Shorten the category name to ${NAME_MAX_LENGTH} characters or fewer.`,
    abort: true,
  });

/**
 * A category's optional orientation prose, validated as both request bodies accept it.
 *
 * Mirrors `OptionalCategoryDescription` in `backend/app/schemas/category.py`, including the
 * blank-folding its `BeforeValidator` performs — which is the one piece of this module that would
 * be wrong if it were guessed rather than reconciled.
 *
 * `categories.description` is nullable, so "this category has no description" already has one
 * representation: `null`. An empty string would be a second, and two representations of one state
 * is a defect waiting to happen. But a textarea cannot submit an absent field: an administrator
 * who clears it submits `''`. The transform folds `''` — and, because `.trim()` has already run,
 * any whitespace-only value — to `null`, so the intent survives and the value posted is the same
 * `null` an omitted field would have produced.
 *
 * That fold is also why no `.min(1)` appears here even though the service's inner type declares
 * one: its blank-folding runs first too, so the bound is unreachable there as well. Adding one
 * here would reject the cleared textarea the API accepts.
 *
 * The ceiling check sits before the transform, and the two orderings agree: `.trim()` has already
 * collapsed a whitespace-only value of any length to `''`, so a submission of six hundred spaces is
 * folded to `null` on both sides rather than being rejected on one of them. It is a `.refine()` over
 * `codePointLength` rather than zod's `.max()` for the reason {@link categoryNameField} gives: the
 * service's `max_length=500` counts code points, and `.max()` would count UTF-16 code units and
 * refuse prose the API accepts.
 *
 * `.nullish()` accepts an explicit `null` and an omitted field, and short-circuits on `null` so
 * the string checks never see it. On a create, absence means the category has no description; on
 * an update, `null` means clear the one that was set, while omitting the field leaves it untouched.
 */
const categoryDescriptionField = z
  .string({ error: 'Write the category description as text.' })
  .trim()
  .refine((value) => codePointLength(value) <= DESCRIPTION_MAX_LENGTH, {
    error: `Shorten the category description to ${DESCRIPTION_MAX_LENGTH} characters or fewer.`,
    abort: true,
  })
  .transform((value) => (value.length === 0 ? null : value))
  .nullish();

/**
 * Validates the body of `POST /api/v1/admin/categories`: a name, and optionally a description.
 *
 * Two members, because two is what only a human can decide. Everything else about the row is the
 * service's to produce, so there is nothing else to submit and nothing else declared here — see
 * the module header on `id`, `slug`, `post_count` and the timestamps.
 *
 * Mirrors `CategoryCreate` in `backend/app/schemas/category.py`, the reconciliation point for both
 * fields. Unknown keys are stripped rather than rejected, which is what keeps a form carrying
 * incidental state in its values from posting a member that model's `extra="forbid"` would answer
 * with a 422.
 *
 * A duplicate name is not detected here; it is a 409 from the API. See the module header.
 *
 * @example
 * ```ts
 * const form = useForm<CategoryCreateFormValues>({
 *   resolver: zodResolver(categoryCreateSchema),
 *   defaultValues: { name: '', description: '' },
 * });
 * ```
 * The `''` default is deliberate and valid: `name` reports "Enter a category name." until it is
 * filled in, and a `description` left untouched folds to `null` on submit.
 */
export const categoryCreateSchema = z.object({
  name: categoryNameField,
  description: categoryDescriptionField,
});

/**
 * The values `@/components/admin/category-form` submits when creating a category.
 *
 * Resolves to `{ name: string; description?: string | null | undefined }`, asserted assignable to
 * `CategoryCreate` from `@/lib/types` so the schema cannot drift from the request contract without
 * failing the type gate.
 */
export type CategoryCreateFormValues = AssertAssignableTo<
  z.infer<typeof categoryCreateSchema>,
  CategoryCreate
>;

/**
 * Validates the body of `PATCH /api/v1/admin/categories/{id}`: whichever members are changing.
 *
 * A genuine partial update. Every member is optional, and an omitted member means "leave this as
 * it is" rather than "set this to null", so renaming a category touches `name` and nothing else.
 * That is what replaces the whole-object replacement the retired predecessor performed, which
 * required a client to resend every field it was not changing and so let a stale copy silently
 * revert whatever it had not refreshed.
 *
 * Derived from {@link categoryCreateSchema} rather than restated, so a bound tightened for a
 * create cannot be forgotten for a rename. The derivation was verified rather than assumed, on the
 * two points where it could have been wrong:
 *
 *   - it makes each member optional WITHOUT making it nullable, so an explicit `{ name: null }`
 *     is still rejected — exactly what `CategoryUpdate.name` requires, and exactly what the
 *     service's `_reject_null_name` validator enforces; and
 *   - it preserves `description`'s blank-folding, so clearing the textarea still posts `null`.
 *
 * An empty object is a valid no-op that parses to `{}`, matching the service's
 * `model_dump(exclude_unset=True)`. A form submitted without edits is a legitimate request with a
 * legitimate outcome, so there is deliberately no "at least one field required" rule.
 *
 * `slug` is absent here for the reason given in the module header, and its absence is the whole
 * point of this schema: a category may be renamed, but its address may not change.
 */
export const categoryUpdateSchema = categoryCreateSchema.partial();

/**
 * The values `@/components/admin/category-form` submits when renaming or re-describing a category.
 *
 * Resolves to `{ name?: string | undefined; description?: string | null | undefined }`, asserted
 * assignable to `CategoryUpdate` from `@/lib/types`. Note that `name` carries no `null` in that
 * union while `description` does — the asymmetry follows the columns, and the guard is what keeps
 * it from being lost in a later edit.
 */
export type CategoryUpdateFormValues = AssertAssignableTo<
  z.infer<typeof categoryUpdateSchema>,
  CategoryUpdate
>;
