"""Three views of an account: what anyone may see, what its owner may see, what it may change.

``users`` is the only relation in this schema read by three different audiences, and this module
is where those audiences are held apart. Three models, three surfaces, no overlap:

* :class:`UserPublic` goes out to anyone. It is the response of ``POST /api/v1/auth/register``
  and of ``GET /api/v1/users/{username}``, and it is the ``author`` member embedded in every
  post, every comment and every administrative row.
* :class:`UserMe` goes out to the authenticated principal, and describes that principal's own
  record only. It is the response of ``GET /api/v1/auth/me`` and of ``PATCH /api/v1/users/me``.
* :class:`UserUpdate` comes in from the authenticated principal, and carries the three profile
  members that principal is permitted to change.

The confidentiality boundary of the whole API lives in this file
---------------------------------------------------------------
:class:`UserPublic` is not one response among many. It is the only user projection permitted to
nest inside another resource, so ``app.schemas.post`` embeds it as a post's author,
``app.schemas.comment`` as a comment's author, and ``app.schemas.admin`` as the subject of an
administrative row. Every one of those surfaces inherits its field list verbatim, which means a
member added here does not leak on one endpoint - it leaks on all of them at once: in the feed a
crawler reads, in the comment thread under every post, and on every profile the sitemap links to.

Four members are therefore withheld, and the omissions are the contract rather than an oversight:

``password_hash``
    Absent from every model in this module and from every model in ``app.schemas``. No schema
    anywhere in this service carries it. ``app.core.security`` produces the argon2id hash and
    verifies a candidate against it; nothing publishes it, logs it or echoes it back.
``email``
    An address no reader has a reason to see. It appears on :class:`UserMe`, where the caller
    *is* the address's owner, and in the administrative user projection. Nowhere else.
``role``
    Authority is not public. Publishing it beside a byline would advertise which accounts are
    administrators - reconnaissance handed out for free, on every post card.
``is_active``
    Whether an account has been suspended is a moderation fact about a person, not profile
    content, and disclosing it would leak an administrative decision to anonymous readers.

Deriving the second model from the first, rather than restating it
-----------------------------------------------------------------
:class:`UserMe` inherits :class:`UserPublic` and adds four members. The two therefore cannot
drift: a description corrected on one is corrected on both, and a field the public projection
stops publishing disappears from the self view in the same edit rather than surviving there
unnoticed.

Inheritance is emphatically **not** permission to embed. :class:`UserMe` is returned by exactly
two routes, both of which have already resolved the caller and are describing that caller's own
record. It must never appear as a nested member of another resource, because nesting is how the
three withheld members it does carry - ``email``, ``role`` and ``is_active``; never
``password_hash``, which it withholds too - would reach an audience that does not own them. A
reviewer checking this property has a one-line test: ``author: UserPublic`` is correct in a
sibling module, and ``author: UserMe`` is a defect.

Exposing the caller's ``email``, ``role`` and ``is_active`` *to the caller* is not a leak. The
caller owns that data, and the account settings screen cannot be written without it. The
prohibition is on the public projection, which is why ``POST /api/v1/auth/register`` answers with
:class:`UserPublic` even though the request came from the account's own owner - a registration
reply has no need of the members :class:`UserMe` adds, so it does not carry them.

What replaced ``Item``
---------------------
The service this repository grew out of had exactly one data contract, and it faced both ways at
once: the same three-field model was the accepted request body and the returned representation.
Two properties of that arrangement are defects this module closes.

The client supplied identity. ``id`` arrived in the request body, the server never generated it
and never checked it for uniqueness. Here ``id`` appears on the two *output* models and on
neither input: it is generated by PostgreSQL, and :class:`UserUpdate` has no member through which
a caller could propose one.

A write accepted whatever a read returned. Because one model served both directions, every field
a response published was a field a request could set - so a projection and a privilege boundary
were the same declaration. Splitting them is what makes ``role`` publishable to its owner and
unsettable by them.

What this module does not do
----------------------------
It declares shapes. There is no session, no statement, no ownership rule, no status code and no
error construction anywhere below. ``app.services.profile_service`` assembles a profile and
applies an update, ``app.repositories.user_repository`` owns every statement,
``app.core.dependencies`` resolves the principal from the bearer token, and
``app.core.exceptions`` renders a failure as the single problem document. This module reads no
configuration: no environment variable, no dotenv file, no import of ``app.core.config``.

It runs no uniqueness check either. ``users.email`` and ``users.username`` are ``CITEXT UNIQUE``,
so the database answers "is this taken?" authoritatively for simultaneous and case-variant
submissions alike, and ``app.services.auth_service`` translates the violation into a ``409``.
Nothing here lower-cases an identifier: an application-side fold would have to be applied on
every write path and every lookup path, and the first path that forgot would admit the duplicate
the ``CITEXT`` index forbids.

There is no collection wrapper here. ``GET /api/v1/users/{username}/posts`` returns
``Page[PostSummary]``, and ``Page`` is declared once, in ``app.core.pagination``, and re-exported
by ``app.schemas.common``.

The two directions disagree about one type, deliberately
-------------------------------------------------------
``avatar_url`` is :class:`~pydantic.HttpUrl` on the way in and ``str`` on the way out. Inbound,
the value is caller-supplied and has to be proved to be an absolute ``http`` or ``https`` URL
before it reaches a column that will be interpolated into an ``<img src>``. Outbound, the value
was already validated when it was stored, so re-parsing it on every byline would cost a parse per
row and would turn a legacy row that no longer parses into a ``500`` on a read path.

The consequence for the service layer is stated on the field itself and repeated here because it
is the one cross-layer obligation this module imposes: :class:`~pydantic.HttpUrl` validates to a
``Url`` object, not to a :class:`str`, so an update must be coerced with ``str(value)`` before it
is assigned to the ``Text`` column.

Import purity
-------------
Four imports: the standard library's :mod:`uuid` and :class:`~datetime.datetime`, the typing
constructs the annotated aliases need, ``pydantic``, and :class:`~app.models.user.UserRole` from
``app.models``.

That last one is a single edge and it points the right way. ``app.models`` does not import
``app.schemas``, so there is no cycle, and taking the enumeration from the module that persists
it means the wire labels and the PostgreSQL ``user_role`` labels are one declaration rather than
two that can disagree the first time a role is added on one side only.

No sibling schema module is imported, and none may be. ``app.schemas.auth`` also bounds a display
name, and the bound below is restated rather than imported from it: an import between siblings
would make this package's import order load-bearing, for a number that has to agree with the
registration contract in any case - see :data:`DISPLAY_NAME_MAX_LENGTH`.
"""

import uuid
from datetime import datetime
from typing import Annotated, Final

from pydantic import (
    BaseModel,
    BeforeValidator,
    ConfigDict,
    EmailStr,
    Field,
    HttpUrl,
    StringConstraints,
    field_validator,
)

from app.models import UserRole

# The module's public contract is these three models, and the ordering is the one RUF022
# enforces. The bounds and annotated aliases below are shared machinery - importable by a test
# or by a validator mirroring them, but not part of the surface `app.schemas.__init__`
# re-exports, exactly as the two length constants in `app.schemas.category` are not. Keep this
# list in step with what the module defines: mypy's strict `no_implicit_reexport` consults it,
# and it is what tells a reader that `UserRole` above is a dependency rather than a re-export.
__all__ = ["UserMe", "UserPublic", "UserUpdate"]


# ---------------------------------------------------------------------------------------
# Profile bounds
#
# `users.display_name`, `users.bio` and `users.avatar_url` are all unbounded `TEXT`, so these
# are the only limits that exist anywhere. The column will store whatever it is handed; this
# schema is the boundary that decides what it is handed.
# ---------------------------------------------------------------------------------------

DISPLAY_NAME_MIN_LENGTH: Final[int] = 1
"""Shortest accepted display name, applied after ``strip_whitespace``.

One character, so a single-glyph name in any script is allowed, combined with stripping so that a
whitespace-only submission is rejected as too short rather than stored as a value that renders as
a blank byline. ``users.display_name`` is ``NOT NULL`` and is rendered unconditionally - in every
post byline, on every post card, at the head of every profile and in the administrative user
table - so an effectively empty name would show as a gap in all four places.
"""

DISPLAY_NAME_MAX_LENGTH: Final[int] = 80
"""Longest accepted display name.

Eighty characters is generous for a person's name in any script while still fitting the
single-line byline, card heading and table cell that render it without wrapping or truncation.

This number must equal the bound ``app.schemas.auth`` applies to the display name supplied at
registration, and it is restated here rather than imported for the reason given under "Import
purity" above: a schema module in this package imports no sibling. The duplication is bounded and
deliberate - two contracts on one column - and it is asymmetric in the safe direction. Widening
this bound while the registration bound stayed put would let an account rename itself to
something it could not have registered as; both numbers are documented, and a change to either
is a change to both.
"""

BIO_MAX_LENGTH: Final[int] = 500
"""Longest accepted biography, in characters.

A bio is a short paragraph of self-description - the block under the heading on a public profile,
and the line beside an author's name in a byline - not an article. Articles are posts. Five
hundred characters comfortably holds two or three sentences, which is what those surfaces render,
and matches the bound ``app.schemas.category`` places on a description for the same reason.

An explicit ceiling is required rather than merely tidy. The column is unbounded ``TEXT``, so
without one a single request could store a megabyte of prose that every subsequent profile read
would transfer and every byline would try to lay out - a storage cost paid once and a rendering
cost paid on every view.
"""


def _blank_to_none(value: object) -> object:
    """Fold a whitespace-only submission to ``None`` before the field is validated.

    ``users.bio`` and ``users.avatar_url`` are both nullable, so "this account has no bio" and
    "this account has no avatar" already have a representation: ``NULL``. An empty string is a
    second representation of the same state, and two representations of one state is a defect
    waiting to happen - ``bio or fallback`` in a template would treat them alike while
    ``bio is None`` would not.

    A form is where the ambiguity comes from. Clearing a populated textarea or input submits
    ``""``, meaning "remove this", and a browser cannot send an absent field from a populated
    form. Folding the blank here means the intent survives: the value reaching the column is the
    same ``NULL`` an omitted field would have produced, and it reaches it through the same code
    path.

    Anything that is not a blank string passes through untouched, including a non-string, so
    Pydantic still reports a genuine type error against the field rather than having it masked by
    a coercion performed here - and ``"not a url"`` still fails the URL rules it should fail.

    Args:
        value: The raw submitted value, before any validation.

    Returns:
        ``None`` if ``value`` is a string with no non-whitespace character; ``value`` unchanged
        otherwise.
    """
    if isinstance(value, str) and not value.strip():
        return None
    return value


DisplayName = Annotated[
    str,
    StringConstraints(
        # Applied before the length rules, so a padded submission is measured after trimming:
        # "  Ada  " is accepted and stored as "Ada", and "   " is rejected as empty rather than
        # accepted as a three-character name that renders as a blank byline.
        strip_whitespace=True,
        min_length=DISPLAY_NAME_MIN_LENGTH,
        max_length=DISPLAY_NAME_MAX_LENGTH,
    ),
]
"""A validated display name, as :class:`UserUpdate` accepts it.

Declared as an alias rather than inline so that the same bounds can be referenced from a second
model without being retyped. No blank-folding is attached, and that is the difference between
this and :data:`OptionalBio`: ``users.display_name`` is ``NOT NULL``, so a cleared control cannot
mean "remove the name" - there is no state for that to produce - and the empty submission is
reported as too short instead.
"""

Bio = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        # A supplied bio must carry something. Absence is expressed by omitting the field or by
        # sending null - see `_blank_to_none`, which is what turns a cleared form control into
        # that absence rather than into a zero-length string stored in a nullable column.
        min_length=1,
        max_length=BIO_MAX_LENGTH,
    ),
]
"""A validated, non-empty biography."""

OptionalBio = Annotated[Bio | None, BeforeValidator(_blank_to_none)]
"""A biography that may legitimately be absent.

``None`` is meaningful and means "this account has no bio": on a patch it is the instruction to
clear one that was set. The blank-folding validator runs first, so ``""`` and ``"   "`` arrive at
the field as ``None`` instead of failing the ``min_length`` rule of the wrapped type.
"""

OptionalAvatarUrl = Annotated[HttpUrl | None, BeforeValidator(_blank_to_none)]
"""An avatar URL that may legitimately be absent, validated as an absolute HTTP(S) URL.

:class:`~pydantic.HttpUrl` accepts only the ``http`` and ``https`` schemes and requires a host, so
``javascript:alert(1)``, ``data:text/html,...``, ``/avatars/me.png`` and ``not a url`` are all
rejected with a ``422`` naming the field. That matters more than input hygiene usually does: the
stored value is interpolated into an ``<img src>`` on every surface that renders the account, so
the scheme allow-list is the control that keeps a profile field from becoming a script vector.

It also carries an inherent length ceiling of 2083 characters - the value Pydantic publishes as
``maxLength`` in the generated schema - so no explicit bound is declared for it here.

The validated value is a ``Url`` object rather than a :class:`str`. See
:attr:`UserUpdate.avatar_url` for the coercion the service layer owes this type.
"""


class UserPublic(BaseModel):
    """An account as anyone may see it: identity, presentation, and when it joined.

    Six fields, and the four that are missing matter as much as the six that are here. It is the
    declared ``response_model`` of two routes::

        @router.post("/auth/register", response_model=UserPublic, status_code=201)
        @router.get("/users/{username}", response_model=UserPublic)

    and it is the ``author`` member of three resources - a post summary, a post detail, a comment -
    plus the subject of an administrative user row, each declared as ``author: UserPublic`` in its
    own module. Because those surfaces share one declaration, this class is the single easiest
    place in the codebase to introduce a data leak, and the single most effective place to prevent
    one.

    Never add ``password_hash``, ``email``, ``role`` or ``is_active`` here
    --------------------------------------------------------------------
    ``password_hash`` belongs to no schema in this service at all. ``email``, ``role`` and
    ``is_active`` belong to :class:`UserMe`, which is returned only to the principal describing
    itself, and to the administrative user projection in ``app.schemas.admin``, which is reachable
    only behind ``require_admin``. Adding any of the four here would publish it simultaneously on
    the public profile, on every post card in the home feed, beside every comment in every thread
    and inside every administrative row - five surfaces from one edit, three of them anonymous.

    Nor a ``post_count``
    -------------------
    A per-author tally is deliberately absent. It would have to be a correlated aggregate, and
    this model is embedded once per row of the home feed - the single most performance-sensitive
    statement in the service, which ``app.repositories.post_repository`` already composes from
    relevance ranking, a category join, author filtering, status scoping, ordering and windowing.
    Adding a subquery per byline would multiply that cost to produce a number no byline renders.
    The one tally the design does publish is ``CategoryPublic.post_count``, which is fetched once
    to populate the home page's filter control rather than once per row.

    Validated from a mapped row rather than constructed by hand
    ----------------------------------------------------------
    ``from_attributes`` is enabled, so a service projects a loaded ``app.models.User`` directly::

        UserPublic.model_validate(post.author)

    That is safe after a commit because ``app.db.session`` builds the session factory with
    ``expire_on_commit=False``, so a loaded attribute is still loaded when this model reads it.
    Under an ``AsyncSession`` the alternative would not be quiet: accessing an expired or
    never-loaded attribute raises ``MissingGreenlet`` at the point of access, so a missing
    ``selectinload`` surfaces here as a failure rather than as an N+1 in production.
    """

    model_config = ConfigDict(
        # Projected from a mapped `app.models.User`, so attribute access has to be a valid input.
        # A plain mapping still validates too, which is what lets a repository that selected
        # individual columns feed this model without materialising an entity.
        from_attributes=True,
        json_schema_extra={
            # One account, carried through all three models in this module with the same values,
            # and the same account `app.schemas.auth` registers in its own example - so /docs
            # reads as a single coherent worked example across both modules rather than as
            # unrelated fragments. The avatar host is `example.com` deliberately: nothing here
            # points at a real image, an account or a credential.
            "example": {
                "id": "3f1a9c74-6b0e-4d52-9a3f-71c2e8b45d10",
                "username": "example-reader",
                "display_name": "Example Reader",
                "bio": "Writes about Python, PostgreSQL and the parts of both that surprise me.",
                "avatar_url": "https://example.com/avatars/example-reader.png",
                "created_at": "2026-01-15T09:30:00Z",
            }
        },
    )

    id: uuid.UUID = Field(
        ...,
        description=(
            "Server-generated identifier, stable for the lifetime of the account. Generated by "
            "PostgreSQL through `gen_random_uuid()` and never supplied by a client. Use it as a "
            "collection key and to compare two references to the same account; use `username` to "
            "build a profile URL."
        ),
    )
    username: str = Field(
        ...,
        description=(
            "Public handle, and a URL path segment: it addresses `GET /api/v1/users/{username}` "
            "and the site's `/u/{username}` profile page, and it appears in that page's canonical "
            "link and sitemap entry. Compared case-insensitively by the database, so `/u/Alice` "
            "and `/u/alice` resolve to this same account. Cannot be changed, so a link built from "
            "it stays valid."
        ),
    )
    display_name: str | None = Field(
        ...,
        description=(
            "Human-readable name to render wherever the account appears - the byline on each of "
            "its posts, the heading of its profile, the author column of a table. Always present "
            "in practice, because `users.display_name` is `NOT NULL` and registration falls back "
            "to the username when none was supplied; typed as nullable so that a client written "
            "against this contract stays correct if a future projection omits it, and so a "
            "consumer is never surprised into rendering the string `null`."
        ),
    )
    bio: str | None = Field(
        ...,
        description=(
            "Short self-description, or null when the account has not written one - the common "
            "case immediately after registration. The key is always present, so a client never "
            "has to distinguish an absent member from a null one; only the value can be null, and "
            "the profile omits the block entirely rather than rendering an empty one."
        ),
    )
    avatar_url: str | None = Field(
        ...,
        description=(
            "Absolute URL of the account's avatar image, or null when it has none. A `str` here "
            "rather than a validated URL type: the value was proved to be an absolute http(s) "
            "URL when it was submitted, so re-parsing it would cost a parse per byline and would "
            "turn an old row that no longer parses into a failed read. Null is expected rather "
            "than exceptional - the avatar component renders the account's initials instead."
        ),
    )
    created_at: datetime = Field(
        ...,
        description=(
            "Instant the account was created, from the database clock, as a timezone-aware "
            "ISO 8601 value in UTC - for example `2026-01-15T09:30:00Z`. Rendered as the "
            "member-since line on a profile. The modification instant is deliberately not "
            "published here; see `UserMe.updated_at`."
        ),
    )


class UserMe(UserPublic):
    """The authenticated principal's own record: the public projection plus what only it may see.

    The declared ``response_model`` of exactly two routes, both of which have already resolved the
    caller and are describing that caller to itself::

        @router.get("/auth/me", response_model=UserMe)
        @router.patch("/users/me", response_model=UserMe)

    It inherits :class:`UserPublic` rather than restating six fields, so the two cannot drift: a
    description corrected on one is corrected on both, and a member the public projection stops
    publishing disappears from here in the same edit instead of surviving unnoticed. Inherited
    fields keep their declaration order, so the serialised member order is ``id``, ``username``,
    ``display_name``, ``bio``, ``avatar_url``, ``created_at``, ``email``, ``role``, ``is_active``,
    ``updated_at`` - the two audit instants are not adjacent, which is the cosmetic price of
    inheriting, and drift-safety is worth more than adjacency.

    Inheritance is not permission to embed
    --------------------------------------
    This class must never appear as a nested member of another resource. ``app.schemas.post``,
    ``app.schemas.comment`` and ``app.schemas.admin`` all embed :class:`UserPublic` as their
    ``author``, and ``author: UserMe`` anywhere in this package is a defect rather than a
    refinement - nesting is precisely how the four members below would reach an audience that
    does not own them.

    Why publishing three withheld members here is not a leak
    -------------------------------------------------------
    Because the audience is the data's owner. A caller reading its own record needs its ``email``
    to see which address the account logs in with, its ``role`` to know whether the administrative
    section applies to it, and its ``is_active`` flag to understand a suspension. Withholding them
    from this response would not protect anyone; it would only leave the account settings screen
    unable to render.

    The prohibition is on the *public* projection, and it is not weakened by this class. Note in
    particular that ``POST /api/v1/auth/register`` answers with :class:`UserPublic` even though the
    request unquestionably came from the account's own owner: a registration reply has no use for
    these four members, so it does not carry them, and the narrower model is the one declared.

    ``password_hash`` is still absent, and always will be. There is no model in this service that
    carries it, and "the caller owns their own data" does not extend to a credential the caller
    cannot use - only ``app.core.security`` ever reads that column.

    Trusted for display, never for authorisation
    -------------------------------------------
    ``role`` here is what the client uses to decide whether to *show* the administrative link. It
    is not what decides whether the caller may *use* it. Every protected operation re-reads the
    persisted role server-side through ``app.core.dependencies.require_admin`` or an ownership
    assertion in the service layer, so hiding a control is user experience and the check behind it
    is the security boundary.
    """

    model_config = ConfigDict(
        # Restated rather than inherited. Pydantic merges the parent's configuration, so this is
        # not strictly required - but a response model whose validation source is only visible one
        # class away is a model someone will eventually break by editing the parent, and stating
        # it also keeps `json_schema_extra` below from replacing a setting declared out of sight.
        from_attributes=True,
        json_schema_extra={
            # The same account as UserPublic's example, extended rather than replaced, so a reader
            # comparing the two documents sees exactly which four members the self view adds. The
            # role is the least-privileged one, which is what a freshly registered account holds.
            "example": {
                "id": "3f1a9c74-6b0e-4d52-9a3f-71c2e8b45d10",
                "username": "example-reader",
                "display_name": "Example Reader",
                "bio": "Writes about Python, PostgreSQL and the parts of both that surprise me.",
                "avatar_url": "https://example.com/avatars/example-reader.png",
                "created_at": "2026-01-15T09:30:00Z",
                "email": "reader@example.com",
                "role": "READER",
                "is_active": True,
                "updated_at": "2026-02-02T18:05:00Z",
            }
        },
    )

    email: EmailStr = Field(
        ...,
        description=(
            "The address this account logs in with. Published only to the account itself and to "
            "an administrator: it appears in no public profile, in no post byline and in no "
            "comment. Stored in a case-insensitive `CITEXT UNIQUE` column and returned in the "
            "form it was registered in, which `email-validator` normalised by lower-casing the "
            "domain and trimming surrounding whitespace while leaving the local part untouched. "
            "Not changeable through this API; see `UserUpdate`."
        ),
    )
    role: UserRole = Field(
        ...,
        description=(
            "The account's authority - `READER`, `AUTHOR` or `ADMIN` - read from the persisted "
            "column rather than from a token claim, so a revoked promotion takes effect on the "
            "next request instead of when an already-issued token expires. Use it to decide "
            "which controls to render; never as an authorisation decision, which the API re-makes "
            "server-side on every protected operation. Not changeable by its holder: only an "
            "administrator can, through `PATCH /api/v1/admin/users/{id}`."
        ),
    )
    is_active: bool = Field(
        ...,
        description=(
            "Whether the account may authenticate. False means an administrator has suspended "
            "it - the reversible half of moderation, which leaves the account's posts and "
            "comments in place - and a suspended principal is rejected before reaching any "
            "protected route. Effectively always true in a response the account itself received, "
            "since a suspended caller cannot authenticate to read this."
        ),
    )
    updated_at: datetime = Field(
        ...,
        description=(
            "Instant the account was last modified, from the database clock, as a timezone-aware "
            "ISO 8601 value in UTC. Equal to `created_at` until the first change, so "
            "`updated_at > created_at` is a reliable `has been edited` test. Published here and "
            "not on the public projection because it is the account's own audit trail - a reader "
            "has no interest in when a byline was last renamed."
        ),
    )


class UserUpdate(BaseModel):
    """The body of ``PATCH /api/v1/users/me``: whichever of three profile members are changing.

    A genuine partial update. All three members are optional, and an omitted member means "leave
    this as it is" rather than "set this to null" - the distinction the service reads by dumping
    only what the caller actually sent::

        changes = payload.model_dump(exclude_unset=True)  # {} for an empty body

    That is what replaces the whole-object replacement the retired ``PUT /items/{item_id}``
    performed. That route required the client to resend every field it was not changing and
    overwrote the stored record with whatever arrived, so a client holding a stale copy silently
    reverted whatever it had not refreshed. Here, writing a bio touches ``bio`` and nothing else.

    ``extra="forbid"`` is the privilege-escalation guard, not a tidiness setting
    -------------------------------------------------------------------------
    It is what turns "we do not accept a role here" from a comment into a rejection. A body
    carrying ``{"role": "ADMIN"}``, ``{"is_active": true}``, ``{"email": ...}``,
    ``{"username": ...}`` or ``{"id": ...}`` produces a ``422`` problem document naming the
    offending key, where Pydantic's permissive default would accept the request and discard the
    field. The difference is the whole control: a discarded field is indistinguishable from an
    honoured one from the outside, so without this setting a privilege-escalation attempt would
    appear to succeed - and would succeed silently at the only layer able to report it.

    This is also where server-owned identity is enforced at the contract boundary. The retired
    model took ``id`` in its request body; this one has no member through which a caller could
    propose an identifier, and the guard makes that unforgeable rather than merely undocumented.

    Only three members, because only three are the account's own presentation
    -----------------------------------------------------------------------
    ``email`` and ``username`` are absent by design, and their absence is enforced by the guard
    above. Both are ``CITEXT UNIQUE`` identity columns, and ``username`` in particular is the
    canonical address of the account: it is in ``GET /api/v1/users/{username}``, in the site's
    ``/u/{username}`` route, in that page's canonical link tag and in every sitemap entry that
    references it. Re-keying it would break links that are already published and indexed, and
    would invalidate every bookmark and share of the profile. This endpoint is scoped to a display
    name, a bio and an avatar, and this model exposes exactly that and nothing adjacent to it.

    ``role`` and ``is_active`` are absent for the sharper reason: they are authority, and authority
    is never self-assigned. Both are changed only by an administrator, through
    ``PATCH /api/v1/admin/users/{id}``, which is gated by ``require_admin`` at router level.

    An empty body is a valid no-op, deliberately
    -------------------------------------------
    ``{}`` validates, dumps to ``{}`` under ``exclude_unset`` and changes nothing. There is no "at
    least one field required" rule, because a settings form submitted without edits is a
    legitimate request with a legitimate outcome, and rejecting it would turn a harmless client
    behaviour into an error a user would have to interpret.

    Null is honoured for two members and refused for one
    --------------------------------------------------
    The asymmetry follows the columns exactly. ``users.bio`` and ``users.avatar_url`` are nullable,
    so ``null`` is a meaningful instruction - "clear this" - and it is carried through:
    ``UserUpdate(bio=None).model_dump(exclude_unset=True)`` is ``{"bio": None}``, which is
    distinguishable from the absent member that ``UserUpdate()`` produces. ``users.display_name``
    is ``NOT NULL``, so there is no state a null could mean, and
    :meth:`reject_null_display_name` reports it as a ``422`` naming the field rather than letting
    it reach the column and surface as a ``500`` describing an integrity violation several layers
    from the request member that caused it.
    """

    model_config = ConfigDict(
        # See the class docstring: an unknown member on an inbound body is always a defect here,
        # and forbidding it is what makes `role`, `is_active`, `email`, `username` and `id`
        # unsettable through this route rather than merely undocumented.
        extra="forbid",
        json_schema_extra={
            # A bio-only patch, chosen over a fuller one because the property readers most often
            # get wrong is that the omitted `display_name` and `avatar_url` are preserved rather
            # than cleared.
            "example": {
                "bio": "Writes about Python, PostgreSQL and the parts of both that surprise me."
            }
        },
    )

    display_name: DisplayName | None = Field(
        default=None,
        description=(
            f"New display name, {DISPLAY_NAME_MIN_LENGTH} to {DISPLAY_NAME_MAX_LENGTH} characters "
            "after surrounding whitespace is removed. Omit the field to leave the current name "
            "unchanged. Null is NOT accepted and neither is a whitespace-only value: "
            "`users.display_name` is `NOT NULL` and is rendered unconditionally, so there is no "
            "state for an empty name to describe. Not required to be unique - two accounts may "
            "share a display name, because `username` is what distinguishes them."
        ),
    )
    bio: OptionalBio = Field(
        default=None,
        description=(
            f"New biography, up to {BIO_MAX_LENGTH} characters after surrounding whitespace is "
            "removed. Omit the field to leave the existing bio untouched; send null, or an empty "
            "string from a cleared form control, to remove it. Plain text rather than Markdown: "
            "it is rendered as text on the profile and beside a byline, never as markup, so no "
            "formatting is interpreted and no markup it contains is honoured."
        ),
    )
    avatar_url: OptionalAvatarUrl = Field(
        default=None,
        description=(
            "New avatar image URL: an absolute http(s) URL, at most 2083 characters. Omit the "
            "field to leave the existing avatar untouched; send null, or an empty string from a "
            "cleared form control, to remove it and fall back to the account's initials. A URL "
            "reference rather than an upload - this API has no multipart pipeline and no object "
            "store - so the image is served by whatever host is named here. Any other scheme is "
            "rejected with 422, because the value is interpolated into an image source. NOTE for "
            "the service layer: the validated value is a Pydantic `Url` object, not a `str`, so "
            "coerce it with `str(value)` before assigning it to the `Text` column; the response "
            "projections publish it as a plain string."
        ),
    )

    @field_validator("display_name")
    @classmethod
    def reject_null_display_name(cls, value: str | None) -> str | None:
        """Reject an explicitly submitted ``{"display_name": null}`` while leaving omission alone.

        The guard rests on a property of Pydantic that is easy to miss and is load-bearing here: a
        field validator runs only for a value the caller actually supplied, never for a field that
        fell back to its default. So this method never sees the ``None`` an omitted
        ``display_name`` leaves behind - ``UserUpdate()`` still validates and still dumps to ``{}``
        under ``exclude_unset=True`` - and it fires only when ``null`` was written into the request
        body on purpose.

        Without it, that ``null`` would survive ``model_dump(exclude_unset=True)`` as a real
        change, reach a ``NOT NULL`` column, and surface as an integrity error: a ``500``
        describing a database constraint, raised several layers away from the request member that
        caused it, instead of a ``422`` naming the field the caller can fix.

        Args:
            value: The submitted display name, already trimmed and length-checked. ``None`` only
                if the caller sent an explicit null.

        Returns:
            ``value`` unchanged, once it is known not to be ``None``.

        Raises:
            ValueError: If ``value`` is ``None``. Pydantic renders it as a field-level entry in the
                ``422`` problem document, keyed to ``display_name``.
        """
        if value is None:
            raise ValueError(
                "display_name may not be null; omit the field to leave the current name unchanged"
            )
        return value
