/* =============================================================================
 * table.test.tsx - the component test for `@/components/ui/table`.
 *
 * WHAT THIS FILE PROTECTS
 *
 * The Table primitive is one of the nine parts of this project's design system
 * authored directly over semantic HTML, because Radix publishes no data grid. Its
 * whole value is that it is a REAL <table>: a stacked-card presentation is very
 * easy to "simplify" into a pile of <div>s, and the moment that happens every
 * screen-reader user loses row and column navigation across all four admin
 * management screens at once - users, posts, comments and categories - with
 * nothing visibly broken to give the regression away.
 *
 * So every assertion below reads the ACCESSIBILITY TREE rather than the tag
 * names: `table`, `rowgroup`, `row`, `columnheader` and `cell` roles, the `scope`
 * that associates a header with its column, and the accessible name a <caption>
 * contributes. That catches the collapse-into-divs regression while staying
 * completely immune to the token and layout changes the design system is free to
 * make.
 *
 * WHAT THIS FILE DELIBERATELY DOES NOT ASSERT
 *
 * The primitive's headline feature is responsive: below the medium breakpoint the
 * header band is hidden and each row presents as a bordered card, and from that
 * breakpoint up the real table is restored inside a horizontal scroll container.
 * All of it is expressed with the styling engine's own `max-md:`/`md:` variants,
 * so NONE of it is observable here. jsdom applies no media query and computes no
 * cascade, so an assertion about the collapsed presentation would either be
 * meaningless or a class-name assertion in disguise.
 *
 * That verification lives in `frontend/tests/e2e/admin.spec.ts`, which drives a
 * real browser at 375, 768 and 1440: stacked cards in the 375 project, and the
 * real table in the 768 and 1440 projects - `max-md:` means "narrower than
 * 48rem", so 768 exactly gets the wide layout. Leave it there.
 *
 * There is therefore no `toHaveClass`, no `className` read, no class-based
 * `querySelector`, no `getComputedStyle`, no snapshot and no `matchMedia` or
 * width stubbing anywhere below. (`vitest.setup.ts` does stub `matchMedia`, but
 * that stub exists so `next-themes` can mount - not as an invitation to fake a
 * breakpoint.) The one piece of the card design that IS semantic rather than
 * visual is `TableCell`'s `label` prop, which carries the column's meaning into
 * the card once the header band is gone, and that is asserted in full.
 *
 * ONE MEASURED JSDOM ARTIFACT, AND HOW IT IS HANDLED
 *
 * `TableCell` renders its `label` in a span that real CSS hides from the medium
 * breakpoint up. jsdom applies no CSS, so that span is visible to the accessible
 * name computation here and a labelled cell computes as "Usernamealice" rather
 * than "alice". A labelled cell's accessible NAME is therefore never asserted
 * below; the label and the value are located by text INSIDE the cell instead,
 * which is true at every width and in every engine. Unlabelled cells have clean
 * names and are queried by role and name directly.
 * ========================================================================== */

import { describe, expect, it } from 'vitest';
import { render, screen, within } from '@testing-library/react';

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import type { AdminUser } from '@/lib/types';

/* -------------------------------------------------------------------------- */
/* Fixtures                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * The three roles the service recognises. Declared locally rather than imported:
 * this spec's dependencies are the primitive under test and the test runner, and
 * a UI primitive test that reached into the API contract layer would fail for a
 * reason that has nothing to do with the table.
 */
type AdminUserRole = 'READER' | 'AUTHOR' | 'ADMIN';

/**
 * One row of the administrative users grid - the real consumer this primitive was
 * written for.
 *
 * The field names are snake_case because they mirror the wire contract exactly;
 * there is no camelCase transformation layer anywhere in this tier, and a fixture
 * that invented one would let a test pass against a shape the API never sends.
 *
 * `id` is a UUID-shaped string and never a caller-chosen integer, because
 * identity in this system is generated by the database. A test fixture is the
 * likeliest place for client-supplied identity to creep back in, so the type
 * itself rules it out.
 */
interface AdminUserRow {
  /** Server-generated identifier. Used here as the row key, as a real grid does. */
  readonly id: string;
  /** Login address. Rendered on the administrative grid and on no public surface. */
  readonly email: string;
  /** Public handle, and the segment the author's profile is addressed by. */
  readonly username: string;
  /**
   * Human-readable name for the grid's name column.
   *
   * NON-NULLABLE, mirroring a `TEXT NOT NULL` column the service derives from the username when an
   * account supplies none - so a fixture typing it as nullable would describe a payload the API
   * cannot send and would license a cell renderer that guards against a value it never receives.
   */
  readonly display_name: string;
  /** The account's authority. */
  readonly role: AdminUserRole;
  /** Whether the account may authenticate. `false` is a deactivated account. */
  readonly is_active: boolean;
  /** Instant the account was created, as an ISO-8601 string, exactly as the API sends it. */
  readonly created_at: string;
  /** Instant the account was last modified, as an ISO-8601 string. Its own column on the grid. */
  readonly updated_at: string;
}

/**
 * Compile-time conformance between the row above and the real wire type, in BOTH directions.
 *
 * The first alias proves the local interface demands nothing the API does not send - the failure mode
 * this fixture actually had, where an invented `post_count` column was rendered and asserted while
 * `AdminUser` has no such member and never sends one. The second proves it omits nothing the API DOES
 * send, which is the other half: `display_name` and `updated_at` were both absent, so the grid was
 * exercised against seven-ninths of the record an administrator really sees.
 *
 * `Readonly<AdminUser>` rather than `AdminUser`, because the row is declared `readonly` field by field
 * and mutability is not part of what is being compared.
 *
 * A TYPE-ONLY import, which is the one thing this spec takes from the contract layer. The file header's
 * rule against reaching into `@/lib/*` is about a primitive's spec not failing for a reason unrelated to
 * the primitive; a type erased at compile time cannot do that, and the alternative - a hand-written
 * shape nothing checks - is what produced the invented column in the first place.
 */
type RowCoversWire = Readonly<AdminUser> extends AdminUserRow ? true : never;
type WireCoversRow = AdminUserRow extends Readonly<AdminUser> ? true : never;
const ROW_MATCHES_WIRE: readonly [RowCoversWire, WireCoversRow] = [true, true];

/** An author with posts to their name. The record every row-scoped assertion below targets. */
const authorRow: AdminUserRow = {
  id: '11111111-1111-4111-8111-111111111111',
  email: 'alice@example.com',
  username: 'alice',
  display_name: 'Alice Nakamura',
  role: 'AUTHOR',
  is_active: true,
  created_at: '2024-01-15T09:30:00Z',
  updated_at: '2024-04-02T11:15:00Z',
};

/** An administrator, so the grid is never single-role and row isolation is testable. */
const adminRow: AdminUserRow = {
  id: '13333333-3333-4333-8333-333333333333',
  email: 'dana@example.com',
  username: 'dana',
  display_name: 'Dana Osei',
  role: 'ADMIN',
  is_active: true,
  created_at: '2024-02-02T14:05:00Z',
  updated_at: '2024-02-02T14:05:00Z',
};

/**
 * A deactivated reader, present so both states of `is_active` are rendered.
 *
 * Its `display_name` is the username, which is what the service writes when an account supplies no
 * name of its own - so this row is the one that shows the name column carrying a derived value rather
 * than a chosen one, and it is never blank or absent.
 */
const deactivatedReaderRow: AdminUserRow = {
  id: '14444444-4444-4444-8444-444444444444',
  email: 'erin@example.com',
  username: 'erin',
  display_name: 'erin',
  role: 'READER',
  is_active: false,
  created_at: '2024-03-21T18:45:00Z',
  updated_at: '2024-03-22T08:00:00Z',
};

/** The grid's records, in the order the administrative listing returns them. */
const adminUserRows: readonly AdminUserRow[] = [authorRow, adminRow, deactivatedReaderRow];

/**
 * The grid's column headings, in order. Every count asserted below is derived from
 * this list and from `adminUserRows`, so adding a column or a record cannot leave
 * a stale expected number behind.
 */
const columnHeadings = [
  'Name',
  'Username',
  'Email',
  'Role',
  'Status',
  'Joined',
  'Updated',
] as const;

/** The <caption> the grid is named by, and the expected accessible name. */
const GRID_CAPTION = 'Registered users';

/** The name used where a grid is named by `aria-label` instead of by a caption. */
const GRID_LABEL = 'Users';

/**
 * A header band and a body are two row groups. Structural, not presentational:
 * `<thead>` and `<tbody>` each expose the `rowgroup` role, and a collapse into
 * `<div>`s would take both away.
 */
const ROW_GROUP_COUNT = 2;

/** How the Status column renders an account's `is_active` flag. */
function statusLabel(isActive: boolean): string {
  return isActive ? 'Active' : 'Deactivated';
}

/* -------------------------------------------------------------------------- */
/* Render helper                                                              */
/* -------------------------------------------------------------------------- */

interface UsersGridOptions {
  /**
   * Text for the grid's `<caption>`, which is what supplies its accessible name.
   * `null` renders no caption at all, leaving the grid unnamed.
   */
  readonly caption?: string | null;
  /** Records to render in the body. An empty list is the pre-data state of an admin screen. */
  readonly rows?: readonly AdminUserRow[];
}

/**
 * Renders the complete composition every case exercises - all six parts, wired the
 * way the administrative users screen wires them, with a `label` on every cell
 * because that is what keeps each value's meaning once the header band is hidden.
 */
function renderUsersGrid(options: UsersGridOptions = {}): void {
  const { caption = GRID_CAPTION, rows = adminUserRows } = options;

  render(
    <Table>
      {/*
       * The one raw element in this file, and it is the primitive's own sanctioned
       * mechanism rather than a way around it: `Table` publishes no `caption` prop
       * and there is no seventh `TableCaption` part, so a caption is supplied as a
       * child - which is exactly what the `caption-bottom` on the table's base
       * classes exists to place. Nothing else here reaches past the six parts.
       */}
      {caption === null ? null : <caption>{caption}</caption>}
      <TableHeader>
        <TableRow>
          {columnHeadings.map((heading) => (
            <TableHead key={heading}>{heading}</TableHead>
          ))}
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((row) => (
          <TableRow key={row.id}>
            <TableCell label="Name">{row.display_name}</TableCell>
            <TableCell label="Username">{row.username}</TableCell>
            <TableCell label="Email">{row.email}</TableCell>
            <TableCell label="Role">{row.role}</TableCell>
            <TableCell label="Status">{statusLabel(row.is_active)}</TableCell>
            <TableCell label="Joined">{row.created_at}</TableCell>
            <TableCell label="Updated">{row.updated_at}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>,
  );
}

/**
 * Locates a record's row by the row's OWN accessible name, which the `row` role
 * derives from its contents.
 *
 * By name rather than by an index into the flat list of rows, so a case cannot
 * silently start asserting against a different record when one is inserted above
 * it. Substring matching rather than an exact string, because a labelled cell
 * contributes its label to that name under jsdom but not in a browser (see the
 * note at the top of this file) - while the record's username is present in both.
 */
function rowFor(record: AdminUserRow): HTMLElement {
  return screen.getByRole('row', { name: (name) => name.includes(record.username) });
}

/* -------------------------------------------------------------------------- */
/* Cases                                                                      */
/* -------------------------------------------------------------------------- */

describe('Table', () => {
  it('renders the whole composition as one real table in the accessibility tree', () => {
    renderUsersGrid();

    // The single most important assertion in the file. If the primitive ever
    // stopped emitting a <table>, this is what would fail first.
    expect(screen.getByRole('table')).toBeInTheDocument();

    // A header band and a body, each exposing its own row group.
    expect(screen.getAllByRole('rowgroup')).toHaveLength(ROW_GROUP_COUNT);

    // One header row plus one row per record. The header row is a row too, which
    // is exactly why the count is derived rather than written out.
    expect(screen.getAllByRole('row')).toHaveLength(adminUserRows.length + 1);

    expect(screen.getAllByRole('columnheader')).toHaveLength(columnHeadings.length);
    expect(screen.getAllByRole('cell')).toHaveLength(adminUserRows.length * columnHeadings.length);
  });

  it('exposes every column heading as a column header, reachable by its name', () => {
    renderUsersGrid();

    for (const heading of columnHeadings) {
      expect(screen.getByRole('columnheader', { name: heading })).toBeInTheDocument();
    }
  });

  it('scopes every column header to its column', () => {
    renderUsersGrid();

    // `scope="col"` is what makes the header-to-cell association programmatic, so a
    // reader announces "Role, AUTHOR" on entering a cell without the cell having to
    // repeat the column name. A styled <td> or a <div> could never carry it.
    for (const header of screen.getAllByRole('columnheader')) {
      expect(header).toHaveAttribute('scope', 'col');
    }
  });

  it('renders rows whose shape is the administrative wire record, not an invented one', () => {
    // The runtime home of the two compile-time aliases above, so the proof is referenced rather than
    // floating: `tsc --noEmit` is what actually enforces it, and this assertion is what makes a reader
    // of the suite aware the enforcement exists.
    expect(ROW_MATCHES_WIRE).toEqual([true, true]);

    renderUsersGrid();

    // And the seven columns are the seven the record can fill. `AdminUser` declares exactly eight
    // members and `id` is the row key rather than a column, so a grid with a different count is either
    // rendering something the API does not send or dropping something it does.
    expect(columnHeadings).toHaveLength(7);
    expect(screen.getAllByRole('columnheader')).toHaveLength(columnHeadings.length);
  });

  it("groups a record's values into its own row, and no other record's", () => {
    renderUsersGrid();

    const row = rowFor(authorRow);

    expect(within(row).getAllByRole('cell')).toHaveLength(columnHeadings.length);

    expect(within(row).getByText(authorRow.display_name)).toBeInTheDocument();
    expect(within(row).getByText(authorRow.username)).toBeInTheDocument();
    expect(within(row).getByText(authorRow.email)).toBeInTheDocument();
    expect(within(row).getByText(authorRow.role)).toBeInTheDocument();
    expect(within(row).getByText(statusLabel(authorRow.is_active))).toBeInTheDocument();
    expect(within(row).getByText(authorRow.created_at)).toBeInTheDocument();
    expect(within(row).getByText(authorRow.updated_at)).toBeInTheDocument();

    // The two instants are DISTINCT on this record, and rendered into distinct cells. Equal fixture
    // values would let a grid that rendered one of them twice pass, which is exactly the mistake a
    // seven-column row invites.
    expect(authorRow.updated_at).not.toBe(authorRow.created_at);

    // Row isolation. Without it every assertion above would still pass against a
    // single flattened row holding all twenty-one values.
    expect(within(row).queryByText(adminRow.username)).toBeNull();
    expect(within(row).queryByText(deactivatedReaderRow.email)).toBeNull();

    // The deactivated record renders the other side of the flag, and its derived display name - which
    // equals its username - is rendered rather than collapsed away as a duplicate.
    const readerRow = rowFor(deactivatedReaderRow);
    expect(
      within(readerRow).getByText(statusLabel(deactivatedReaderRow.is_active)),
    ).toBeInTheDocument();

    // Its display name IS its username, because that is what the service writes for an account that
    // supplied none - so the value appears in two cells rather than one, and the grid renders both
    // rather than treating the second as a duplicate to elide.
    expect(deactivatedReaderRow.display_name).toBe(deactivatedReaderRow.username);
    expect(within(readerRow).getAllByText(deactivatedReaderRow.display_name)).toHaveLength(2);
  });

  it('takes its accessible name from a caption', () => {
    renderUsersGrid({ caption: GRID_CAPTION });

    // A grid announced only as "table" with a row and column count tells a
    // screen-reader user nothing about which of the four admin grids they are in.
    expect(screen.getByRole('table')).toHaveAccessibleName(GRID_CAPTION);
    expect(screen.getByRole('table', { name: GRID_CAPTION })).toBeInTheDocument();
  });

  it('renders without a caption, leaving the grid unnamed', () => {
    renderUsersGrid({ caption: null });

    const table = screen.getByRole('table');
    expect(table).toBeInTheDocument();
    expect(table).not.toHaveAccessibleName();

    // The caption is optional and its absence is not an error - but a real grid
    // still names itself, so the sanctioned alternative is asserted next.
    expect(screen.getAllByRole('columnheader')).toHaveLength(columnHeadings.length);
  });

  it('can be named by aria-label instead, which rides the spread onto the table', () => {
    render(
      <Table aria-label={GRID_LABEL}>
        <TableBody>
          <TableRow>
            <TableCell>{authorRow.username}</TableCell>
          </TableRow>
        </TableBody>
      </Table>,
    );

    expect(screen.getByRole('table', { name: GRID_LABEL })).toBeInTheDocument();
  });

  it('renders a cell label beside its value, inside the same cell', () => {
    // The semantic half of the card presentation: once the header band is hidden
    // below the medium breakpoint this label is the ONLY thing carrying the
    // column's meaning, visually and to a screen reader.
    render(
      <Table aria-label={GRID_LABEL}>
        <TableBody>
          <TableRow>
            <TableCell label="Role">{authorRow.role}</TableCell>
          </TableRow>
        </TableBody>
      </Table>,
    );

    expect(screen.getByText('Role')).toBeInTheDocument();
    expect(screen.getByText(authorRow.role)).toBeInTheDocument();

    // Both belong to the same cell. A label rendered as a sibling of the cell would
    // satisfy the two assertions above and still be wrong.
    const cell = screen.getByRole('cell');
    expect(within(cell).getByText('Role')).toBeInTheDocument();
    expect(within(cell).getByText(authorRow.role)).toBeInTheDocument();
  });

  it('renders no label when the label prop is omitted, leaving the value as the cell name', () => {
    render(
      <Table aria-label={GRID_LABEL}>
        <TableBody>
          <TableRow>
            <TableCell>{authorRow.role}</TableCell>
          </TableRow>
        </TableBody>
      </Table>,
    );

    // Self-describing content - a row-actions menu, a lone avatar - takes no label,
    // and an unlabelled cell's accessible name is exactly its value.
    expect(screen.getByRole('cell', { name: authorRow.role })).toBeInTheDocument();
    expect(screen.queryByText('Role')).toBeNull();
  });

  it('forwards attributes to the underlying semantic element on all six parts', () => {
    render(
      <Table id="registered-users" data-testid="grid">
        <TableHeader data-testid="header">
          <TableRow data-testid="header-row">
            <TableHead data-testid="head">Username</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody data-testid="body">
          <TableRow data-testid="body-row">
            <TableCell data-testid="cell" label="Username">
              {authorRow.username}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>,
    );

    // `Table` renders a wrapper around the <table>, so this pins WHICH element the
    // spread reaches: the table itself, never the container.
    const table = screen.getByRole('table');
    expect(screen.getByTestId('grid')).toBe(table);
    expect(table).toHaveAttribute('id', 'registered-users');

    expect(screen.getAllByRole('rowgroup')).toContain(screen.getByTestId('header'));
    expect(screen.getAllByRole('rowgroup')).toContain(screen.getByTestId('body'));
    expect(screen.getAllByRole('row')).toContain(screen.getByTestId('header-row'));
    expect(screen.getAllByRole('row')).toContain(screen.getByTestId('body-row'));
    expect(screen.getByTestId('head')).toBe(screen.getByRole('columnheader', { name: 'Username' }));
    expect(screen.getAllByRole('cell')).toContain(screen.getByTestId('cell'));

    // The spread cannot clobber the header's scope default.
    expect(screen.getByTestId('head')).toHaveAttribute('scope', 'col');
  });

  it('renders an empty body as a named table with its headings and no cells', () => {
    // What every admin screen shows before its first page of data arrives. The
    // headings must survive, or the grid reads as an unlabelled empty box.
    renderUsersGrid({ rows: [] });

    expect(screen.getByRole('table')).toHaveAccessibleName(GRID_CAPTION);
    expect(screen.getAllByRole('rowgroup')).toHaveLength(ROW_GROUP_COUNT);
    expect(screen.getAllByRole('columnheader')).toHaveLength(columnHeadings.length);

    // Only the header row remains, and there is no cell at all.
    expect(screen.getAllByRole('row')).toHaveLength(1);
    expect(screen.queryAllByRole('cell')).toHaveLength(0);
  });

  it('makes the scroll container a named, focusable region when scrollRegionLabel is given', () => {
    // For a grid with nothing focusable inside it: such a scrollport cannot be
    // scrolled by keyboard at all, because there is nothing within it to focus.
    render(
      <Table aria-label={GRID_LABEL} scrollRegionLabel={GRID_LABEL}>
        <TableBody>
          <TableRow>
            <TableCell>{authorRow.username}</TableCell>
          </TableRow>
        </TableBody>
      </Table>,
    );

    const region = screen.getByRole('region', { name: GRID_LABEL });
    expect(region).toHaveAttribute('tabindex', '0');

    // The region names the scrollport and the table names the data; both survive.
    expect(screen.getByRole('table', { name: GRID_LABEL })).toBeInTheDocument();
    expect(screen.getByRole('cell', { name: authorRow.username })).toBeInTheDocument();
  });

  it('leaves the scroll container out of the accessibility tree by default', () => {
    // Every admin row carries a link or a row-action trigger, so focus already
    // enters the container and an extra tab stop would be one to tab past on every
    // pass. The attributes are applied together or not at all.
    renderUsersGrid();

    expect(screen.queryByRole('region')).toBeNull();
    expect(screen.getByRole('table')).toBeInTheDocument();
  });

  it('keeps real table semantics in the prose variant', () => {
    // The prose variant hands presentation to the typography plugin, but it exists
    // so a table inside rendered Markdown is still wrapped by this one module. If
    // that route ever stopped producing table semantics, an author's table would
    // become unnavigable while looking perfectly fine.
    render(
      <Table variant="prose" aria-label="Search strategies">
        <TableHeader>
          <TableRow>
            <TableHead>Strategy</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell>Weighted tsvector</TableCell>
          </TableRow>
        </TableBody>
      </Table>,
    );

    expect(screen.getByRole('table', { name: 'Search strategies' })).toBeInTheDocument();
    expect(screen.getAllByRole('rowgroup')).toHaveLength(ROW_GROUP_COUNT);
    expect(screen.getByRole('columnheader', { name: 'Strategy' })).toHaveAttribute('scope', 'col');
    expect(screen.getByRole('cell', { name: 'Weighted tsvector' })).toBeInTheDocument();
  });
});
