/**
 * The REST contract of the blog API, mirrored once for the whole presentation tier.
 *
 * Every wire shape the Next.js tier reads or writes is declared here and nowhere else.
 * `@/lib/api/client` and the typed wrappers beside it, `@/lib/seo`, `src/middleware.ts`, the
 * hooks, the providers, the route segments and the components all import their contract types
 * from this module, so a single edit here is the only edit needed when the service's contract
 * moves. A second, competing declaration of any shape below - inlined in a component, redeclared
 * in an API wrapper, or inferred from a validator - is a defect, because the entire value of this
 * file is that one declaration is the tier's single source of truth.
 *
 * ## Provenance: this file is a mirror, not a design
 *
 * Nothing here is invented. Each declaration mirrors a backend model field for field, and each of
 * those backend modules names this file as its counterpart. Paths below are relative to
 * `backend/app/`:
 *
 * | Declared here                                                         | Mirrored from         |
 * | --------------------------------------------------------------------- | --------------------- |
 * | `Page`                                                                | `core/pagination.py`  |
 * | `ProblemDetail`, `ValidationErrorItem`                                | `schemas/common.py`   |
 * | `RegisterRequest`, `LoginRequest`, `RefreshRequest`, `TokenPair`      | `schemas/auth.py`     |
 * | `UserPublic`, `UserMe`, `UserUpdate`                                  | `schemas/user.py`     |
 * | `CategorySummary`, `CategoryPublic`, `CategoryCreate`, and the rest   | `schemas/category.py` |
 * | `PostCreate`, `PostUpdate`, `PostSummary`, `PostDetail`, and the rest | `schemas/post.py`     |
 * | `CommentCreate`, `CommentUpdate`, `CommentPublic`                     | `schemas/comment.py`  |
 * | `LikeSummary`                                                         | `schemas/like.py`     |
 * | `AdminUser`, `AdminPost`, `AdminComment`, `AdminStats`, and the rest  | `schemas/admin.py`    |
 * | `UserRole`, `PostStatus`, `CommentStatus`                             | `models/*.py`         |
 *
 * The three label unions mirror the `user_role`, `post_status` and `comment_status` PostgreSQL
 * types declared in `models/user.py`, `models/post.py` and `models/comment.py` respectively.
 *
 * When a backend model changes, read it and change this file to match. Do not adjust a shape here
 * to suit a component: that hides a contract break behind a type that still compiles.
 *
 * ## Wire conventions - the four that break silently if you get them wrong
 *
 * 1. **Field names stay snake_case, exactly as the service emits them.** There is no camel-case
 *    mapping layer anywhere in this tier - not in the HTTP client, not in the wrappers, not in a
 *    response interceptor. Re-spelling a field in the other convention produces a type that
 *    compiles perfectly and a value that is `undefined` at run time, which is the single most
 *    expensive mistake available in this module. Every property name below is the literal JSON key.
 * 2. **Primary keys and foreign keys are `string`.** Identity is a UUID generated by PostgreSQL
 *    through `gen_random_uuid()` and serialised as its canonical text form; it is never a number
 *    and is never supplied by a client.
 * 3. **Instants are ISO-8601 `string`, never `Date`.** The service serialises `timestamptz`
 *    columns to JSON text and `JSON.parse` has no date type, so a field typed `Date` compiles and
 *    then throws on the first date method call. `@/lib/format` is the module that turns these
 *    strings into human-readable labels.
 * 4. **`T | null` and `field?: T` mean different things and are not interchangeable.** A response
 *    field the service always sends but may send as `null` is `T | null`. A request field the
 *    client may leave out is optional. On a request, optional-and-nullable (`field?: T | null`)
 *    is used only where the service accepts an explicit `null` as an instruction to clear the
 *    value; where it rejects `null` and treats omission as "leave unchanged", the field is
 *    optional but not nullable. Each request field below records which of the two it is.
 *
 * ## What this module deliberately does not do
 *
 * - **No imports.** It is the bottom of `@/lib`'s dependency graph: it imports no package, no
 *   validator, no API wrapper, no provider, hook, component or route. The arrow points only
 *   outward, which is what lets `src/middleware.ts` - which runs in the Edge runtime - pull a
 *   type from here without dragging anything executable across the boundary.
 * - **No keyword-declared constant objects.** The three closed label sets are string-literal
 *   unions, not the keyword-declared constant construct TypeScript also offers for this purpose.
 *   The choice is load-bearing rather than stylistic: `src/middleware.ts` reaches `UserRole`
 *   through `import type { UserRole } from '@/lib/types'`, and a type-only import elides the
 *   object such a construct needs at run time, leaving nothing behind to read a member from. A
 *   union of string literals has no run-time representation to elide, and it compares directly
 *   against the literal string the service sent.
 * - **No environment access.** The API base URL belongs to `@/lib/api/client`, and the canonical
 *   site origin and site name belong to `@/lib/seo`. Nothing is read from the environment here,
 *   and the service's own configuration is not reachable from this tier at all.
 * - **No view models, form state, UI state or generic response wrapper.** Only shapes that cross
 *   the network. Every declaration traces to a backend model; a type with no counterpart there
 *   does not belong in this file.
 * - **No barrel.** There is no `@/lib/index`; consumers import `@/lib/types` directly.
 *
 * The one exception to "declarations only" is the four readonly literal member arrays below
 * (`USER_ROLES`, `POST_STATUSES`, `COMMENT_STATUSES`, `POST_SORTS`). A picker in the admin tables
 * and the feed's sort control need the members at run time, and deriving each union from its array
 * with `(typeof ARRAY)[number]` keeps one source of truth instead of a list and a union that can
 * drift apart. They are literal tuples: importing this module still performs no work and has no
 * side effect.
 *
 * ## Governing standards
 *
 * No user-specified rules were provided for this project. The binding constraints are therefore
 * the technical plan's own enterprise standards, four of which govern this module: explicit API
 * contracts (`Page` carries five fields, `ProblemDetail` is the one error shape, and no per-verb
 * response wrapper is modelled anywhere); server-owned identity (no request shape accepts an
 * identifier, a slug, a lifecycle state, a publication instant, a view count or an author
 * reference); API versioning (every shape describes a resource beneath `/api/v1`); and blocking
 * quality gates (this file compiles under `tsc --noEmit` and lints at `--max-warnings=0`).
 *
 * @module
 */

/* -------------------------------------------------------------------------------------------------
 * Shared envelopes
 *
 * Two shapes are used by more than one namespace: the page envelope every collection returns, and
 * the problem document every failure returns. They are declared first because everything else
 * either travels inside one or is reported through the other.
 * ---------------------------------------------------------------------------------------------- */

/**
 * One window onto a larger collection, plus the counts needed to navigate it.
 *
 * Every collection endpoint returns this envelope, with exactly one documented exception: the home
 * feed (`GET /api/v1/posts`), an author's published posts (`GET /api/v1/users/{username}/posts`), a
 * post's comment thread (`GET /api/v1/posts/{id}/comments`) and each administrative table
 * (`GET /api/v1/admin/{users,posts,comments}`) all arrive as a page. That uniformity is the reason
 * one pagination component can drive all of them.
 *
 * **The one exception is the category taxonomy, and it is specified rather than accidental.**
 * `GET /api/v1/categories` returns a **bare JSON array** of {@link CategoryPublic} at the top level
 * - the service declares that route's response model as a plain list, and `app.schemas.category`
 * records it as "the single sanctioned exception to the envelope rule in this API". The taxonomy is
 * administrator-curated and bounded, and a filter offering only some of its terms would silently
 * hide every post filed exclusively under the rest, so the whole set is returned in one request.
 * `@/lib/api/categories` therefore returns `CategoryPublic[]`; reading an `items` member off that
 * answer yields `undefined` while type-checking cleanly, because the mismatch is with the wire shape
 * rather than with any signature. See {@link CategoryPublic}.
 *
 * **Exactly five fields.** `has_next`, `has_prev`, `offset`, cursors and hypermedia links are all
 * absent and must stay absent: every one is computable from the five values here, and a sixth
 * field would be a sixth thing this module, the service's model and the endpoint reference all
 * have to agree about. `@/hooks/use-pagination` and `@/components/ui/pagination` are written
 * against these names.
 *
 * Two properties of the arithmetic are contractual rather than incidental, and a client that
 * ignores either renders the wrong control:
 *
 * - `pages` is `ceil(total / page_size)`, so an **empty collection reports `pages: 0`, not `1`**.
 *   A page control should render nothing at all in that case.
 * - A `page` beyond the last one is **not an error**. The service echoes back whatever `page` was
 *   requested, returns an empty `items` array and raises nothing, so a caller can recognise that
 *   it has run off the end rather than being silently redirected to a page it never asked for.
 *
 * Requests are **validated** server-side, not adjusted: `page` must be at least 1 with no upper
 * limit, and `page_size` must be between 1 and 100, defaulting to 20 when it is not sent. An
 * out-of-range value is **rejected**, not corrected - `?page_size=1000` and `?page_size=0` each
 * answer `422` with the uniform {@link ProblemDetail} document naming the parameter, so a caller
 * that sends a bad window learns it went wrong instead of silently receiving a different window
 * than it asked for. A client offering a page-size control must therefore keep its options inside
 * 1..100 rather than relying on the service to trim them.
 *
 * @typeParam T - The already-projected response shape of a single row, for example
 * {@link PostSummary}, {@link CommentPublic} or {@link AdminUser}.
 */
export interface Page<T> {
  /**
   * The rows on this page only, already projected into their response shape. Empty when the
   * collection is empty and when `page` is beyond `pages`.
   */
  items: T[];
  /**
   * How many rows match the request in total, ignoring the window. This is the unwindowed count,
   * not the length of `items`, so it is what a "N results" label should read from.
   */
  total: number;
  /**
   * The 1-based page that was requested, echoed back verbatim and never clamped - which is what
   * lets a caller detect a request beyond the end of the collection.
   */
  page: number;
  /**
   * The window size that was applied - the value the request asked for, echoed back after passing
   * the service's 1..100 validation, or 20 when the request named none. It is never a different
   * number than the one that was accepted, because an unacceptable one never produces a page at
   * all. `items` may be shorter than this on the last page.
   */
  page_size: number;
  /** How many pages `total` rows occupy at this `page_size`. Zero when `total` is zero. */
  pages: number;
}

/**
 * One field-level validation failure, as carried in {@link ProblemDetail.errors}.
 *
 * Produced only by the service's request-validation handler, one entry per rejected field, so a
 * form can attach each message to the control that caused it instead of showing a single opaque
 * banner. All three properties are always present; none is optional.
 */
export interface ValidationErrorItem {
  /**
   * Dotted path of the offending value in the syntax of the submitted body, for example `title` or
   * `category_ids.0`. Empty only in the rare case that the failure cannot be attributed to a named
   * field, so a form should fall back to a non-field-specific presentation when it is blank.
   */
  field: string;
  /** Human-readable description of the failure, suitable for rendering beside the control. */
  message: string;
  /**
   * Machine-readable validator identifier, such as `string_too_short` or `value_error`. Use it to
   * branch on a failure kind; use {@link ValidationErrorItem.message} to show one.
   */
  type: string;
}

/**
 * The single error shape of the entire API, served as `application/problem+json`.
 *
 * There is exactly one error contract and this is it. The service renders this document for every
 * failure path without exception - domain errors raised by the service layer, request-validation
 * failures, framework-raised status codes (so even a 404 on a path that does not exist arrives in
 * this shape), rate-limit rejections and unhandled exceptions alike. `@/lib/api/client` normalises
 * every non-2xx response into this one shape, so no consumer needs a second error branch and no
 * consumer should invent one.
 */
export interface ProblemDetail {
  /**
   * Stable, machine-readable identifier for the *kind* of problem. The service's namespace is
   * `/errors/` followed by a kebab-case name - `/errors/not-found`, `/errors/unauthorized`,
   * `/errors/forbidden`, `/errors/conflict`, `/errors/validation-error`,
   * `/errors/rate-limit-exceeded`.
   *
   * This is the value to branch on, and the only member of this document that is safe to branch
   * on: it is part of the contract, where {@link ProblemDetail.title} and
   * {@link ProblemDetail.detail} are prose and may be reworded. Compare it against the literal the
   * service emits - a relative reference, not an absolute URL - because a consumer matching on an
   * invented absolute form would silently never match.
   */
  type: string;
  /** Short human-readable summary of the problem kind. Constant for a given `type`. */
  title: string;
  /**
   * The HTTP status code, repeated in the body so a logged or forwarded document stays
   * self-describing. Always equal to the status of the response that carried it.
   */
  status: number;
  /** Human-readable explanation of this particular occurrence. Safe to show to a person. */
  detail: string;
  /**
   * Path of the request the failure occurred on, without its query string - deliberately, since
   * the query is not part of the failure's identity and is where stray credentials end up.
   */
  instance: string;
  /**
   * Correlation identifier for the request that failed, identical to the `X-Request-ID` header on
   * the same response - the service writes both from one value, so they cannot disagree. Present
   * on every failure path, which is what makes it safe to render in an error surface and quote in
   * a support report: every structured log line for that request carries the same value, so one
   * string is enough to find the failure server-side.
   */
  request_id: string;
  /**
   * Per-field detail, carried only by a request-validation failure - and then never empty.
   *
   * **Omission is the only no-errors state.** The service publishes this member as an optional
   * array with `minItems: 1` and no `null` branch, and its single assembly point normalises both
   * absent forms away: `errors` is left out of the document entirely when there is no per-field
   * detail, rather than serialised as `null` or as `[]`. So `undefined` is the one thing a
   * consumer ever sees in place of a list, and the mirror says exactly that rather than a
   * superset of it - the tuple-with-rest spelling below is how TypeScript expresses "an array
   * with at least one element".
   *
   * The practical consequence is that `if (problem.errors)` is a complete test. There is no
   * empty list to guard against and no `null` to guard against, so a length check adds nothing,
   * and inside the branch `errors[0]` is known to exist rather than merely typed as though it
   * might.
   */
  errors?: [ValidationErrorItem, ...ValidationErrorItem[]];
}

/* -------------------------------------------------------------------------------------------------
 * Closed label sets
 *
 * Three native PostgreSQL label types travel on the wire as their uppercase labels. Each is
 * mirrored as a readonly literal tuple plus a union derived from it, so the members exist once: the
 * tuple is what an admin picker or a filter control maps over, and the union is what every shape
 * below and `src/middleware.ts` type against. Deriving the union from the tuple - rather than
 * writing the members twice - is what stops the two drifting apart.
 *
 * Member order is the order the service's own label types declare, which is meaningful in each
 * case, so a control that renders a tuple in order gets a sensible sequence for free.
 * ---------------------------------------------------------------------------------------------- */

/**
 * The three levels of authority an account can hold, least privilege first.
 *
 * Ordered by privilege, matching the declaration order of the service's `user_role` type, so a
 * picker rendering this tuple lists the least powerful option first.
 */
export const USER_ROLES = ['READER', 'AUTHOR', 'ADMIN'] as const;

/**
 * An account's authority.
 *
 * - `READER` - may read published posts, comment and like. The role every new account is given.
 * - `AUTHOR` - may additionally create, edit, publish and delete **its own** posts.
 * - `ADMIN` - may additionally act on any account's posts and comments and reach the
 *   administrative namespace.
 *
 * What each role permits is enforced server-side on every request. `src/middleware.ts` and a
 * hidden control are user experience, not a security boundary: the middleware keeps a reader from
 * loading the admin route group, and the service independently re-checks authority behind every
 * administrative endpoint.
 *
 * Declared as a union of string literals, rather than as a keyword-declared constant object,
 * specifically so `src/middleware.ts` can reach it with
 * `import type { UserRole } from '@/lib/types'` and still compare against a string literal.
 */
export type UserRole = (typeof USER_ROLES)[number];

/**
 * The three states of a post's publication lifecycle, in lifecycle order.
 *
 * Matches the declaration order of the service's `post_status` type, so a status filter renders
 * draft-to-archived rather than alphabetically.
 */
export const POST_STATUSES = ['DRAFT', 'PUBLISHED', 'ARCHIVED'] as const;

/**
 * A post's lifecycle state.
 *
 * The lifecycle is an explicit state and deliberately not a boolean flag, because publishing is a
 * first-class transition rather than a field a general partial update could flip:
 *
 * - `DRAFT` - authored but not public, and the state every post is created in. Absent from the
 *   feed, from every category filter and from its author's public profile, and readable only by
 *   its author or an administrator. Carries no {@link PostSummary.published_at}.
 * - `PUBLISHED` - public and discoverable: listed in the feed, filterable, crawlable and
 *   listed in the sitemap. Reaching this state **requires** a publication instant, which a
 *   database check constraint enforces rather than leaving to application code, so
 *   {@link PostSummary.published_at} is never `null` on a post in this state.
 * - `ARCHIVED` - withdrawn from the public surface after having been published, without being
 *   deleted.
 *
 * Transitions are performed by `POST /api/v1/posts/{id}/publish` and
 * `POST /api/v1/posts/{id}/unpublish` for an author, and by
 * `PATCH /api/v1/admin/posts/{id}/status` for an administrator. No request shape in this module
 * carries `status` except {@link AdminPostStatusUpdate}.
 */
export type PostStatus = (typeof POST_STATUSES)[number];

/**
 * The three moderation states a comment can be in, in queue order.
 *
 * Matches the declaration order of the service's `comment_status` type, so the moderation control
 * lists the pending state a moderator is acting on first.
 */
export const COMMENT_STATUSES = ['PENDING', 'APPROVED', 'REJECTED'] as const;

/**
 * A comment's moderation state.
 *
 * Moderation is an explicit state rather than a boolean approval flag, because the two invisible
 * states are not the same thing - one is work still to be done, the other is a decision already
 * taken - and collapsing them would leave the queue indistinguishable from the pile of rejections
 * behind it:
 *
 * - `PENDING` - submitted but not yet moderated, and the state every comment is created in.
 *   Invisible in the public thread; visible to an administrator as the moderation queue.
 * - `APPROVED` - moderated and public. The only state a public caller ever sees, because the
 *   public thread query filters on it explicitly.
 * - `REJECTED` - moderated and refused. Invisible in the public thread, and still movable back.
 *
 * Read-only from a client's point of view: only `PATCH /api/v1/admin/comments/{id}/status` changes
 * it, through {@link AdminCommentStatusUpdate}.
 */
export type CommentStatus = (typeof COMMENT_STATUSES)[number];

/* -------------------------------------------------------------------------------------------------
 * Authentication - POST /api/v1/auth/{register,login,refresh,logout} and GET /api/v1/auth/me
 *
 * Bearer-token authentication, held entirely in these four shapes plus the two user projections:
 * registration answers with {@link UserPublic}, and `GET /api/v1/auth/me` answers with
 * {@link UserMe}. The password policy the client must mirror lives in `@/lib/validation/auth`; this
 * module carries the wire shapes only, because a length or character-class rule expressed as a type
 * would go stale the moment the service tightened it.
 * ---------------------------------------------------------------------------------------------- */

/**
 * Body of `POST /api/v1/auth/register`. Returns {@link UserPublic}, not {@link UserMe}.
 *
 * That distinction is contractual and worth stating at the call site, because assuming otherwise
 * is a runtime error rather than a type error: the registration response carries no `email`, no
 * `role`, no `is_active` and no `updated_at`. A client that needs the full self-view calls
 * `GET /api/v1/auth/me` after logging in, which is the route that answers with {@link UserMe}.
 *
 * Note what is **absent**: there is no role field, and adding one would turn account creation into
 * privilege escalation. Every account is created as `READER`; only an administrator can change a
 * role afterwards, through {@link AdminUserUpdate}. There is likewise no identifier - identity is
 * generated by the database.
 *
 * The service rejects any property not declared here outright, rather than ignoring it, so a stray
 * field is reported as a validation failure instead of being silently dropped.
 *
 * A duplicate email or username is reported as a conflict rather than a validation failure, and
 * both are matched case-insensitively: an address or handle differing from an existing one only in
 * case is a duplicate, not a new account.
 */
export interface RegisterRequest {
  /**
   * The address the account will log in with. Validated for deliverable syntax and normalised by
   * the service; never published on any public surface.
   */
  email: string;
  /**
   * Public handle, and a URL path segment - it is what addresses the account's profile at
   * `/u/{username}`. Unique case-insensitively.
   */
  username: string;
  /**
   * The new password in plaintext, over TLS, hashed with argon2id by the service and never stored
   * or logged in the clear. Held to the policy mirrored in `@/lib/validation/auth`.
   */
  password: string;
  /**
   * Human-readable name shown wherever the account appears. Optional: omit it, or send `null`, to
   * have the username used instead, since the service guarantees every account a usable name at
   * registration rather than making every view substitute one.
   */
  display_name?: string | null;
}

/**
 * Body of `POST /api/v1/auth/login`. Returns {@link TokenPair}.
 *
 * **Wire note, worth reading before "fixing" anything here.** This shape is the documented JSON
 * contract of the route, and `@/lib/api/auth` sends it as JSON. The same route *additionally*
 * accepts the OAuth 2 password-grant form, `application/x-www-form-urlencoded`, which is what makes
 * the **Authorize** control on the service's generated documentation usable for exploring protected
 * routes. That form's field is named `username` by the grant while this API's identifier is an
 * email address, so the value that goes into the form's `username` box is the account's **email**.
 * Only one credential model exists - this one - and any mapping between the two encodings belongs
 * to `@/lib/api/auth`, not here.
 *
 * The password is deliberately **not** held to the registration policy on this route. Publishing
 * the policy to an unauthenticated caller tells them which candidates they need not try, and any
 * account whose password predates a later tightening must still be able to sign in. A wrong
 * address and a wrong password fail identically, with the same status and the same body, so this
 * route cannot be used to discover which addresses are registered.
 */
export interface LoginRequest {
  /**
   * The address the account registered with, matched case-insensitively so the exact casing used at
   * registration does not have to be reproduced.
   */
  email: string;
  /** The account's password, verified against the stored argon2id hash. */
  password: string;
}

/**
 * Body of `POST /api/v1/auth/refresh` and of `POST /api/v1/auth/logout`. Refresh returns a new
 * {@link TokenPair}; logout revokes the presented token and returns no resource.
 *
 * Sent as **JSON** on both routes - unlike {@link LoginRequest}, which also has a form-encoded
 * equivalent. Refresh rotates: the presented token is revoked as the replacement is issued, so a
 * token is single-use and presenting a revoked one fails. `@/lib/api/client` is the only module
 * that should call refresh, from its single retry-once-on-unauthorised path, because two components
 * refreshing concurrently would race to invalidate each other's replacement.
 */
export interface RefreshRequest {
  /** The refresh token from the most recent {@link TokenPair}. */
  refresh_token: string;
}

/**
 * The credential pair returned by `POST /api/v1/auth/login` and `POST /api/v1/auth/refresh`.
 *
 * The two tokens are different kinds of thing and are not interchangeable:
 *
 * - {@link TokenPair.access_token} is a short-lived signed JWT carrying the subject, the role and
 *   its own issue and expiry instants. It is what goes in the `Authorization: Bearer` header.
 *   Never trust a claim decoded from it in the client for an authorisation decision - the service
 *   re-checks authority on every request, and a claim read client-side is a display hint at best.
 * - {@link TokenPair.refresh_token} is an **opaque** high-entropy string. It is *not* a JWT, has no
 *   readable structure, and must never be decoded, parsed or inspected client-side. The service
 *   stores only its hash, so it cannot be recovered server-side either.
 */
export interface TokenPair {
  /** Signed JWT to send as `Authorization: Bearer <token>` on every authenticated request. */
  access_token: string;
  /**
   * Opaque credential used only to obtain the next pair. Not a JWT; carries no readable claims.
   */
  refresh_token: string;
  /**
   * The authentication scheme to use, fixed by the service. Typed as the literal because there is
   * exactly one accepted value, so a mismatch is a compile error rather than a runtime surprise.
   */
  token_type: 'bearer';
  /**
   * Seconds until {@link TokenPair.access_token} expires - **seconds, not milliseconds**. Convert
   * at the point of use if a timer needs milliseconds; do not multiply this value into storage, or
   * the unit stops matching the field name.
   */
  expires_in: number;
}

/* -------------------------------------------------------------------------------------------------
 * Users - GET /api/v1/users/{username}, GET /api/v1/users/{username}/posts,
 *         PATCH /api/v1/users/me, GET /api/v1/auth/me
 *
 * Two projections of one relation, and the difference between them is a confidentiality boundary
 * rather than a convenience. {@link UserPublic} is what anyone may see; {@link UserMe} is what an
 * account may see about itself.
 * ---------------------------------------------------------------------------------------------- */

/**
 * An account as anyone may see it: the response of `GET /api/v1/users/{username}` and the shape
 * embedded wherever an author appears.
 *
 * This is the **only** user projection that may be nested inside another resource, and it is the
 * exact type of the author reference on {@link PostSummary}, {@link PostDetail},
 * {@link CommentPublic}, {@link AdminPost} and {@link AdminComment}. Using it everywhere means one
 * byline component renders an author on the feed, on a post, in a comment thread and in an
 * administrative table without a per-surface variant.
 *
 * It withholds the email address, the role, the active flag and - needless to say - the password
 * hash. Do not add them: this shape is embedded in responses that any anonymous caller can fetch,
 * so a field added here is a field published to the world. An account's own private fields live on
 * {@link UserMe}, and the administrative view lives on {@link AdminUser}.
 */
export interface UserPublic {
  /**
   * Server-generated identifier, stable for the lifetime of the account. Use it as a React key and
   * as a comparison target; use {@link UserPublic.username} to build a link.
   */
  id: string;
  /**
   * Public handle, and a URL path segment: this is what addresses the profile at `/u/{username}`.
   * Matched case-insensitively by the service, so `/u/Alice` and `/u/alice` resolve to one account.
   */
  username: string;
  /**
   * Human-readable name to render wherever the account appears - the byline on each of its posts,
   * the heading of its profile, the author column of a table.
   *
   * Never `null` and never absent. The underlying column is `TEXT NOT NULL` and registration
   * derives the value from the username when no name was supplied, so the service has no state
   * this member could report as null — which is why it is typed non-nullable here rather than
   * defensively widened: a mirror wider than the state the database can hold would make every
   * consumer write a fallback for a case that cannot occur, and would let an incorrect projection
   * type-check.
   */
  display_name: string;
  /** Short self-description, or `null` when the account has not written one. */
  bio: string | null;
  /**
   * Absolute URL of the account's avatar image, or `null` when it has none - in which case render
   * the initials fallback rather than a broken image. The service validates the scheme on write, so
   * a stored value is always an `http` or `https` URL.
   */
  avatar_url: string | null;
  /** Instant the account was created, as an ISO-8601 string. */
  created_at: string;
}

/**
 * The authenticated account's own record: the response of `GET /api/v1/auth/me` and of
 * `PATCH /api/v1/users/me`.
 *
 * Returned **only** to the principal it describes, which is why it may carry the fields
 * {@link UserPublic} withholds. Never render one of these where a public author reference belongs -
 * that is what {@link UserPublic} is for - and never store one in a cache keyed by anything other
 * than the session.
 *
 * Extends {@link UserPublic} rather than restating its fields, so a component that accepts an
 * author reference accepts this too and there is exactly one place a public field is declared.
 */
export interface UserMe extends UserPublic {
  /** The address this account logs in with. Published nowhere else in the API. */
  email: string;
  /**
   * This account's authority. Safe to use to decide which controls to *show*; not safe to treat as
   * an authorisation decision, which the service makes independently on every request.
   */
  role: UserRole;
  /**
   * Whether the account may authenticate. `false` means an administrator has deactivated it, at
   * which point its credentials stop working while its content stays in place.
   */
  is_active: boolean;
  /** Instant the account was last modified, as an ISO-8601 string. */
  updated_at: string;
}

/**
 * Body of `PATCH /api/v1/users/me`. Returns the updated {@link UserMe}.
 *
 * A genuine partial update: every field is optional, and an omitted field is left **unchanged**
 * rather than cleared. The service rejects any property not declared here, which is what makes the
 * email address, the username, the role, the active flag and the identifier unsettable through this
 * route rather than merely undocumented.
 *
 * The two nullable fields and the one non-nullable field behave differently on purpose, and the
 * difference is the whole reason they are typed differently: sending `null` for a nullable field is
 * the instruction to **clear** it, while `null` for the display name is rejected, because the
 * underlying column is non-nullable and there is no meaningful "no name" state to clear to.
 */
export interface UserUpdate {
  /**
   * New display name. Omit to leave the current one unchanged. `null` is **not** accepted, and
   * neither is a whitespace-only value.
   */
  display_name?: string;
  /**
   * New biography. Omit to leave the current one unchanged; send `null` to clear one that was set.
   * A cleared form control submitting an empty string is folded to `null` by the service, so
   * "remove this" survives whichever of the two a form sends.
   */
  bio?: string | null;
  /**
   * New avatar image URL: an absolute `http` or `https` URL. Omit to leave the current one
   * unchanged; send `null` to remove it. The scheme allow-list is a security control, not input
   * hygiene - the stored value is interpolated into an image source on every surface that renders
   * the account.
   */
  avatar_url?: string | null;
}

/* -------------------------------------------------------------------------------------------------
 * Categories - GET /api/v1/categories, GET /api/v1/categories/{slug},
 *              POST|PATCH|DELETE /api/v1/admin/categories
 *
 * The taxonomy the feed filters by and the administrative screen manages. Two projections, and one
 * pair of request shapes reused by the administrative routes - there is no separate administrative
 * category input, because an administrator creating a category sends exactly what the schema below
 * describes.
 * ---------------------------------------------------------------------------------------------- */

/**
 * The slim category projection, embedded in a post's category list.
 *
 * Deliberately carries no description and no post count, so rendering the badges on a feed card
 * costs no aggregate query per post. Fetch {@link CategoryPublic} when a count is actually needed.
 */
export interface CategorySummary {
  /** Server-generated identifier - the value that goes in {@link PostCreate.category_ids}. */
  id: string;
  /** Human-readable display label, unique across the taxonomy. */
  name: string;
  /**
   * URL-safe identifier used in canonical links and as the feed's category filter value. Derived
   * from the name by the service at creation and stable thereafter, which is what lets a filtered
   * feed URL be shared and crawled.
   */
  slug: string;
}

/**
 * A category in full: the element type of the bare array `GET /api/v1/categories` returns, and the
 * response of `GET /api/v1/categories/{slug}`.
 *
 * **`GET /api/v1/categories` answers with a bare JSON array of this type, NOT with a
 * {@link Page}.** It is the single sanctioned exception to the envelope rule across the whole API,
 * and it is specified rather than accidental: the service declares that route's response model as a
 * plain list, and the router carries a comment recording why it must not be normalised. Three
 * reasons, and they compound - the taxonomy is administrator-curated and bounded, so nothing a
 * reader does grows it; the home page needs all of it before it can render the filter control; and a
 * filter offering only some of the terms is not an incomplete filter but a wrong one, silently
 * hiding every post filed exclusively under a term left out.
 *
 * So `@/lib/api/categories` returns `CategoryPublic[]`. Do not "normalise" that to an envelope and
 * do not reach for an `items` member on the answer: there is none, the read yields `undefined`, the
 * filter control renders no options, and nothing reports an error - the mismatch is with the wire
 * shape rather than with either signature, so both sides still type-check. The envelope, and with it
 * `@/hooks/use-pagination` and `@/components/ui/pagination`, governs the feed, profile posts, comment
 * threads and the administrative tables; this one route sits outside it by design.
 *
 * Extends {@link CategorySummary}, so anything that renders a badge from the slim shape renders one
 * from this too.
 */
export interface CategoryPublic extends CategorySummary {
  /** Orientation prose for the category, or `null` when none was written. */
  description: string | null;
  /**
   * How many **published** posts are filed under this category. Drafts and archived posts are
   * excluded, so the number always matches what a reader would find by selecting the filter.
   */
  post_count: number;
  /** Instant the category was created, as an ISO-8601 string. */
  created_at: string;
}

/**
 * Body of `POST /api/v1/admin/categories`. Returns the created {@link CategoryPublic}.
 *
 * Accepts neither an identifier nor a slug. Identity is generated by the database, and the slug is
 * derived from the name by the service - which matters beyond tidiness: the slug is the category's
 * canonical URL, and a client-supplied one could collide with an existing category or change on a
 * later edit and break every link and every crawled page that pointed at it.
 *
 * A duplicate name is reported as a conflict rather than accepted, so the taxonomy cannot grow two
 * categories a reader would read as the same one.
 */
export interface CategoryCreate {
  /** Display label for the category. Surrounding whitespace is removed by the service. */
  name: string;
  /** Optional orientation prose. Omit it or send `null` for a category with no description. */
  description?: string | null;
}

/**
 * Body of `PATCH /api/v1/admin/categories/{id}`. Returns the updated {@link CategoryPublic}.
 *
 * A genuine partial update: an omitted field is left unchanged. As with
 * {@link CategoryCreate}, no identifier and no slug - renaming a category does **not** re-derive
 * its slug, precisely so that a link already published keeps resolving.
 */
export interface CategoryUpdate {
  /** New display label. Omit to leave it unchanged; `null` is **not** accepted. */
  name?: string;
  /**
   * New orientation prose. Omit to leave it unchanged; send `null` to clear one that was set.
   */
  description?: string | null;
}

/* -------------------------------------------------------------------------------------------------
 * Posts - GET /api/v1/posts, GET /api/v1/posts/{slug}, POST /api/v1/posts,
 *         PATCH|DELETE /api/v1/posts/{id}, POST /api/v1/posts/{id}/{publish,unpublish}
 *
 * The centre of the domain. Two request shapes, two response projections, and one sort union that
 * types the feed's ordering parameter.
 *
 * No request shape here accepts an identifier, a slug, a lifecycle state, a publication instant, a
 * view count or an author reference. Every one of those is owned by the service: identity and
 * timestamps by the database, the slug by the slug deriver at creation, the author by the resolved
 * principal, and the lifecycle by the publish and unpublish transitions. Putting any of them on a
 * request shape would hand a client control of a value the whole design exists to keep server-side.
 * ---------------------------------------------------------------------------------------------- */

/**
 * The orderings `GET /api/v1/posts` accepts, in its `sort` query parameter.
 *
 * Exactly two members and no third. `recent` is the service's default when the parameter is absent.
 */
export const POST_SORTS = ['recent', 'relevance'] as const;

/**
 * The feed's ordering parameter.
 *
 * - `recent` - newest published first, which is the default and the only sensible ordering when no
 *   search term was supplied, since relevance against an empty query is meaningless.
 * - `relevance` - ranked by full-text match quality against the `q` parameter, weighted so a hit in
 *   a title outranks one in the body.
 *
 * The home feed keeps this in the URL alongside the search term, the category filter and the page
 * number, which is what makes any result set linkable, shareable, crawlable and correct under
 * browser back and forward navigation.
 */
export type PostSort = (typeof POST_SORTS)[number];

/**
 * Body of `POST /api/v1/posts`. Returns the created {@link PostDetail}.
 *
 * A created post is always a `DRAFT` and is absent from every public surface until it is published
 * through `POST /api/v1/posts/{id}/publish`. There is no way to create a published post in one
 * request, and that is deliberate: publication is the transition that stamps the publication
 * instant the database requires, so it stays a distinct, auditable step rather than becoming a
 * flag set at creation time.
 *
 * The service rejects any property not declared here, and sanitises the authored content on write.
 */
export interface PostCreate {
  /**
   * The post's headline. The service derives the slug from it, de-duplicating on collision, so two
   * posts may share a title without either getting an ambiguous URL.
   */
  title: string;
  /**
   * Optional short summary shown on feed cards and used as the page description in metadata. Omit
   * it or send `null` and the surface falls back to the opening of the content.
   */
  excerpt?: string | null;
  /** The post body as Markdown. Sanitised server-side on write and again at render. */
  content: string;
  /**
   * Optional absolute `http` or `https` URL of the hero image, also used as the social card. Omit
   * it or send `null` for a post with no cover, in which case the default social card is used.
   */
  cover_image_url?: string | null;
  /**
   * Identifiers of the categories to file the post under, taken from {@link CategorySummary.id}.
   * Optional - omit it for an uncategorised post and the service stores an empty set. The count per
   * post is bounded server-side, and an identifier that matches no category is rejected rather than
   * silently dropped.
   */
  category_ids?: string[];
}

/**
 * Body of `PATCH /api/v1/posts/{id}`. Returns the updated {@link PostDetail}.
 *
 * A **genuine partial update**, and structurally every field of {@link PostCreate} made optional:
 * an omitted field is left unchanged rather than reset to a default. That is the point of the
 * route - it replaces a whole-object replacement in which every unspecified field was silently
 * overwritten.
 *
 * Authority is checked server-side: an author may patch only their own post, an administrator may
 * patch any, and neither can change the lifecycle state through this route.
 */
export interface PostUpdate {
  /**
   * New headline. Omit to leave it unchanged; `null` is **not** accepted. Editing the title does
   * **not** re-derive the slug - the canonical URL is fixed at creation so a published link and a
   * crawled page keep resolving.
   */
  title?: string;
  /** New short summary. Omit to leave it unchanged; send `null` to clear one that was set. */
  excerpt?: string | null;
  /** New Markdown body. Omit to leave it unchanged; `null` is **not** accepted. */
  content?: string;
  /**
   * New absolute `http` or `https` URL of the hero image. Omit to leave it unchanged; send `null`
   * to remove the cover.
   */
  cover_image_url?: string | null;
  /**
   * The post's **complete** category set after the update - this replaces the existing set rather
   * than adding to it, so send every category the post should end up with, and send an empty array
   * to file it under none. Omit the field to leave the current set untouched; `null` is **not**
   * accepted.
   */
  category_ids?: string[];
}

/**
 * A post as a list renders it: the element type of `GET /api/v1/posts` and of
 * `GET /api/v1/users/{username}/posts`, both wrapped in a {@link Page}.
 *
 * **It carries no body content, deliberately.** A feed page returns up to a hundred of these, and
 * including the Markdown body would multiply every home-feed, profile and dashboard response by the
 * size of the articles in it. Fetch {@link PostDetail} when the body is actually going to be
 * rendered. Do not add a content field here.
 *
 * Public callers only ever see posts in the `PUBLISHED` state through these routes; the author
 * dashboard is what surfaces a `DRAFT`, and only to its own author or an administrator.
 */
export interface PostSummary {
  /**
   * Server-generated identifier. This is what the mutation routes address - patch, delete, publish,
   * unpublish, likes and comments all take the identifier, not the slug.
   */
  id: string;
  /** The post's headline, rendered as the card's heading. */
  title: string;
  /**
   * URL-safe identifier the canonical URL is built from: the post is read at
   * `GET /api/v1/posts/{slug}` and rendered at `/blog/{slug}`. Unique, and fixed at creation so it
   * never changes - which is exactly what a canonical link and a sitemap entry require.
   */
  slug: string;
  /** Short summary, or `null` when the author wrote none. */
  excerpt: string | null;
  /** Absolute URL of the post's hero image, or `null` when it has no cover. */
  cover_image_url: string | null;
  /**
   * Lifecycle state. `PUBLISHED` for anything reached through a public listing; a `DRAFT` or an
   * archived post appears only in the author dashboard or an administrative table.
   */
  status: PostStatus;
  /**
   * Instant the post became public, as an ISO-8601 string, or `null` while it has never been
   * published. Non-null whenever {@link PostSummary.status} is `PUBLISHED` - a database check
   * constraint guarantees the pair, so the two can be relied on together. Null-tolerance here is a
   * correctness requirement rather than defensive padding, because the dashboard renders drafts.
   */
  published_at: string | null;
  /** How many times the post's page has been viewed. */
  view_count: number;
  /** Instant the post was created, as an ISO-8601 string. Distinct from its publication instant. */
  created_at: string;
  /**
   * The account that wrote the post, as the public projection - never the private one, and never a
   * bare identifier, so a card can render a byline without a second request.
   */
  author: UserPublic;
  /**
   * The categories the post is filed under, as the slim projection. Empty for an uncategorised
   * post, so the array is always present and never needs a null check.
   */
  categories: CategorySummary[];
}

/**
 * A post in full: the response of `GET /api/v1/posts/{slug}`, `POST /api/v1/posts`,
 * `PATCH /api/v1/posts/{id}` and both lifecycle transitions.
 *
 * Extends {@link PostSummary} with the two fields a detail view needs, so every component that
 * accepts a summary - card, byline, category badges, reading time - accepts this unchanged.
 *
 * The detail route resolves a post by **slug**, and a post that is not `PUBLISHED` is readable
 * through it only by its author or an administrator; to any other caller such a slug simply does
 * not exist, which is what keeps a draft from leaking through a guessed URL.
 */
export interface PostDetail extends PostSummary {
  /**
   * The post body as Markdown, exactly as its author wrote it after server-side sanitisation.
   * Rendered through the sanitising Markdown pipeline, never injected as raw HTML.
   */
  content: string;
  /** Instant the post was last modified, as an ISO-8601 string. */
  updated_at: string;
}

/* -------------------------------------------------------------------------------------------------
 * Comments - GET|POST /api/v1/posts/{id}/comments, PATCH|DELETE /api/v1/comments/{id}
 *
 * Threaded discussion under a post. One self-referencing response shape carries the whole tree, so
 * a thread arrives in a single request rather than one per depth level.
 * ---------------------------------------------------------------------------------------------- */

/**
 * Body of `POST /api/v1/posts/{id}/comments`. Returns the created {@link CommentPublic}.
 *
 * Carries neither the post nor the author: the post comes from the path, the author from the bearer
 * token's resolved principal. It also carries no moderation state - a new comment is always
 * `PENDING` and becomes publicly visible only once an administrator approves it, which is why an
 * optimistic insertion should be rendered as the author's own pending contribution rather than as a
 * published reply.
 */
export interface CommentCreate {
  /** The comment text. Sanitised server-side on write. */
  body: string;
  /**
   * Identifier of the comment this one replies to. **Supplying it is what makes this a reply**;
   * omit it, or send `null`, for a top-level comment. The parent must belong to the same post,
   * which the service verifies rather than trusting.
   */
  parent_id?: string | null;
}

/**
 * Body of `PATCH /api/v1/comments/{id}`. Returns the updated {@link CommentPublic}.
 *
 * The body is the only editable field, matching the route's purpose exactly. A comment cannot be
 * re-parented after the fact - moving a reply would silently rewrite a conversation someone else
 * took part in - and it cannot be moderated here: that is {@link AdminCommentStatusUpdate}'s job.
 *
 * Optional, mirroring the service: a patch with nothing set validates and changes nothing. `null`
 * is **not** accepted, and neither is a whitespace-only value - deleting a comment is a delete, not
 * an empty edit. Authority is checked server-side: the comment's author or an administrator, nobody
 * else.
 */
export interface CommentUpdate {
  /** Replacement comment text. Omit to change nothing; `null` is **not** accepted. */
  body?: string;
}

/**
 * A comment as a thread renders it: the element type of `GET /api/v1/posts/{id}/comments`, wrapped
 * in a {@link Page}, and the response of the create, edit and moderate routes.
 *
 * Threading is realised by the self-referencing {@link CommentPublic.replies} array: the paged
 * envelope windows **top-level** comments, and each one arrives with its replies already nested, so
 * a page of the thread is one request regardless of how deep the conversation goes. Render it with
 * a component that recurses on `replies`.
 *
 * A public caller sees only `APPROVED` comments, in the tree and in the nested replies alike,
 * because the thread query filters on that state explicitly.
 */
export interface CommentPublic {
  /** Server-generated identifier. The value the edit and delete routes address. */
  id: string;
  /**
   * The post this comment belongs to. Always present, including on a nested reply, so a moderation
   * table can link back to the post without walking up the tree.
   */
  post_id: string;
  /**
   * The comment this one replies to, or `null` when it is top-level. A consumer that has already
   * placed the comment inside its parent's replies array does not need this; a flat table does.
   */
  parent_id: string | null;
  /** The account that wrote the comment, as the public projection. */
  author: UserPublic;
  /** The comment text, already trimmed and already sanitised. */
  body: string;
  /**
   * Moderation state. **Read-only from a client's point of view**: it is never settable through
   * {@link CommentCreate} or {@link CommentUpdate}, and only
   * `PATCH /api/v1/admin/comments/{id}/status` changes it.
   */
  status: CommentStatus;
  /** Instant the comment was written, as an ISO-8601 string. */
  created_at: string;
  /** Instant the comment was last modified, as an ISO-8601 string. */
  updated_at: string;
  /**
   * The comments answering this one, nested. Empty for a leaf, so the array is always present and
   * never needs a null check - recurse on it directly.
   */
  replies: CommentPublic[];
}

/* -------------------------------------------------------------------------------------------------
 * Likes - PUT|DELETE /api/v1/posts/{id}/like, GET /api/v1/posts/{id}/likes
 *
 * One response shape and, deliberately, no request shape at all.
 * ---------------------------------------------------------------------------------------------- */

/**
 * A post's like state: the response of **all three** like routes.
 *
 * There is no request shape for liking, and that is not an omission. All three routes are bodyless
 * because everything they need is already addressed - the post by the path, the account by the
 * bearer token's resolved principal - so there is nothing left for a body to carry.
 *
 * Two properties shape how the client should be written:
 *
 * - **Every one of the three routes returns this same summary** - `PUT /api/v1/posts/{id}/like`,
 *   `DELETE /api/v1/posts/{id}/like` and `GET /api/v1/posts/{id}/likes` - so an optimistic update
 *   settles on the response it already has and needs no follow-up read. Liking, unliking and
 *   reading all leave the client holding the authoritative count.
 * - **Liking is idempotent by construction.** The service's composite key makes a repeated like a
 *   no-op rather than a second row, so `PUT` is safely retryable and a double-click cannot inflate
 *   a count. Unliking something never liked is equally harmless.
 *
 * `GET /api/v1/posts/{id}/likes` needs no bearer token: for an anonymous caller
 * {@link LikeSummary.liked_by_caller} is simply `false`, which is also the correct thing to render.
 */
export interface LikeSummary {
  /** Identifier of the post this summary describes, echoed back so a cache can key on it. */
  post_id: string;
  /** How many distinct accounts have liked the post. Never inflated by a repeated request. */
  like_count: number;
  /**
   * Whether the account making the request has liked the post. `false` for an anonymous caller, so
   * this can drive the control's pressed state without a separate authentication check.
   */
  liked_by_caller: boolean;
}

/* -------------------------------------------------------------------------------------------------
 * Administration - /api/v1/admin/*
 *
 * Seven shapes, all behind an administrator-only guard applied at the router level server-side so
 * no individual route can omit it. `src/middleware.ts` keeps a non-administrator from loading the
 * route group, and every endpoint below independently re-checks the role: hiding a control is user
 * experience, and the server-side check is the security boundary.
 *
 * The administrative projections differ from the public ones in what they span, not merely in what
 * they expose: an administrative listing crosses lifecycle and moderation states a public listing
 * filters out, which is the entire reason the screens exist. Category management reuses
 * {@link CategoryCreate} and {@link CategoryUpdate} - there is deliberately no administrative
 * category input, because an administrator sends exactly the same body a category needs.
 * ---------------------------------------------------------------------------------------------- */

/**
 * An account as the administrative user table renders it: the element type of
 * `GET /api/v1/admin/users`, wrapped in a {@link Page}, and the response of
 * `PATCH /api/v1/admin/users/{id}`.
 *
 * Exposes the email address, the role and the active flag, which {@link UserPublic} withholds -
 * that is what the table is for. It still carries **no password hash**, and none may be added: the
 * hash never leaves the service, not even to an administrator, because a screen that can display it
 * is a screen that can leak it.
 *
 * Deliberately not an extension of {@link UserPublic}: it omits the biography and the avatar, which
 * a management table does not render, and keeping the two shapes independent stops a field added
 * for a public byline from appearing in an administrative payload by inheritance.
 */
export interface AdminUser {
  /** Server-generated identifier. The value the role, deactivation and delete routes address. */
  id: string;
  /** The address this account logs in with. Published on no public surface. */
  email: string;
  /** Public handle, and the path segment its profile is addressed by. */
  username: string;
  /**
   * Human-readable name for the table's name column. Non-nullable for the same reason as on
   * {@link UserPublic}: both mirror one `TEXT NOT NULL` column, so the two declarations must
   * agree with it and with each other.
   */
  display_name: string;
  /** The account's authority. Changed through {@link AdminUserUpdate}. */
  role: UserRole;
  /**
   * Whether the account may authenticate. `false` means it is deactivated: its credentials stop
   * working while its posts and comments stay in place, which is the reversible alternative to
   * deleting it.
   */
  is_active: boolean;
  /** Instant the account was created, as an ISO-8601 string. */
  created_at: string;
  /** Instant the account was last modified, as an ISO-8601 string. */
  updated_at: string;
}

/**
 * Body of `PATCH /api/v1/admin/users/{id}`. Returns the updated {@link AdminUser}.
 *
 * Both fields are optional and a partial update leaves the other untouched, so promoting an account
 * and deactivating one are independent operations that happen to share a route. Sending neither is
 * accepted and changes nothing.
 *
 * Neither field is nullable: omission is how "unchanged" is expressed, and an explicit `null` is
 * rejected rather than being written to a non-nullable column. Nothing else about an account is
 * settable here - not the email address, not the username, not the password.
 */
export interface AdminUserUpdate {
  /** New authority for the account. Omit to leave it unchanged; `null` is **not** accepted. */
  role?: UserRole;
  /**
   * Whether the account may authenticate. Omit to leave it unchanged; `null` is **not** accepted.
   */
  is_active?: boolean;
}

/**
 * A post as the administrative post table renders it: the element type of
 * `GET /api/v1/admin/posts`, wrapped in a {@link Page}, and the response of
 * `PATCH /api/v1/admin/posts/{id}/status`.
 *
 * Spans **every** lifecycle state, including drafts and archived posts, which no public listing
 * returns - that reach is the reason the screen exists.
 *
 * Carries no body content and no excerpt: a management table lists and acts on posts, it does not
 * render them, so the payload stays small even across the whole corpus.
 */
export interface AdminPost {
  /** Server-generated identifier. The value the status and delete routes address. */
  id: string;
  /** The post's title as its author wrote it. */
  title: string;
  /** URL-safe path segment, so a row can link to the post's public page when it is published. */
  slug: string;
  /** Lifecycle state, across the full range rather than the published subset. */
  status: PostStatus;
  /**
   * Instant the post first became public, as an ISO-8601 string, or `null` while it has never been
   * published - which is the normal case for the drafts this table is largely there to show.
   */
  published_at: string | null;
  /** Number of times the post's detail page has been viewed. */
  view_count: number;
  /**
   * The account that wrote the post, as the public projection - the same shape the public surfaces
   * use, so the author column reuses the byline component rather than a table-specific variant.
   */
  author: UserPublic;
  /** Instant the post was created, as an ISO-8601 string. */
  created_at: string;
  /** Instant the post was last modified, as an ISO-8601 string. */
  updated_at: string;
}

/**
 * Body of `PATCH /api/v1/admin/posts/{id}/status`. Returns the updated {@link AdminPost}.
 *
 * **Required, not optional**: the route exists to move a post to a named state, so a request that
 * names none has nothing to do and is rejected rather than silently accepted.
 *
 * This is the administrative counterpart of the author's publish and unpublish transitions, and it
 * reaches states those do not - archiving in particular. The service maintains the publication
 * instant alongside the state, so a state change here cannot leave the pair inconsistent.
 */
export interface AdminPostStatusUpdate {
  /** The lifecycle state to move the post to. */
  status: PostStatus;
}

/**
 * A comment as the moderation queue renders it: the element type of
 * `GET /api/v1/admin/comments`, wrapped in a {@link Page}, and the response of
 * `PATCH /api/v1/admin/comments/{id}/status`.
 *
 * Spans **all** moderation states, which is what makes it a queue rather than a second view of the
 * public thread. It is deliberately **flat**: it carries the parent reference but no nested
 * replies, because moderation acts on one comment at a time and a table row is not a conversation.
 */
export interface AdminComment {
  /** Server-generated identifier. The value the status and delete routes address. */
  id: string;
  /** The post this comment was written on, so a row can link to the discussion it belongs to. */
  post_id: string;
  /**
   * The comment this one replies to, or `null` when it is top-level. Useful as context when
   * moderating a reply, since the queue is flat.
   */
  parent_id: string | null;
  /** The account that wrote the comment, as the public projection. */
  author: UserPublic;
  /** The comment's text, sanitised on write. */
  body: string;
  /** Moderation state, across the full range rather than the approved subset. */
  status: CommentStatus;
  /** Instant the comment was written, as an ISO-8601 string. */
  created_at: string;
  /** Instant the comment was last modified, as an ISO-8601 string. */
  updated_at: string;
}

/**
 * Body of `PATCH /api/v1/admin/comments/{id}/status`. Returns the updated {@link AdminComment}.
 *
 * **Required, not optional**, for the same reason as {@link AdminPostStatusUpdate}: the route's
 * whole purpose is to name the state to move to.
 *
 * Because the moderation states are three rather than a boolean, this route can also move a comment
 * *back* - a rejection is reversible, and a decision made in error is not permanent.
 */
export interface AdminCommentStatusUpdate {
  /** The moderation state to move the comment to. */
  status: CommentStatus;
}

/**
 * Aggregate counts for the administrative overview screen: the response of
 * `GET /api/v1/admin/stats`.
 *
 * Four totals, computed server-side across the whole corpus, and what
 * `@/components/admin/stat-card` renders. Every count spans all states - all posts in every
 * lifecycle state, all comments in every moderation state, all accounts active and deactivated -
 * because an overview that quietly excluded the drafts and the moderation queue would understate
 * exactly the work the dashboard exists to surface.
 */
export interface AdminStats {
  /** Total number of registered accounts, active and deactivated alike. */
  user_count: number;
  /** Total number of posts in every lifecycle state, drafts and archived posts included. */
  post_count: number;
  /** Total number of comments in every moderation state, pending and rejected included. */
  comment_count: number;
  /** Total number of categories in the taxonomy. */
  category_count: number;
}
